# Test pages

# The job name must be "pages", and the html must be in "public/" and put in an artifact.
pages:
  image: docker.io/library/debian@sha256:de3eac83cd481c04c5d6c7344cd7327625a1d8b2540e82a8231b5675cef0ae5f  # debian:9
  script:
    - apt-get update && apt-get -y install doxygen graphviz
    - doxygen doxygen/ingopcs-toolkit.doxyfile
    - mv apidoc/html public/
  artifacts:
    paths:
    - public
    expire_in: 1 hour
