/*
 * Licensed to Systerel under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Systerel licenses this file to you under the Apache
 * License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#ifndef SOPC_CUSTOM2_Types_H_
#define SOPC_CUSTOM2_Types_H_ 1

#include "custom2_enum_types.h"
#include "sopc_buffer.h"
#include "sopc_builtintypes.h"
#include "sopc_encodeabletype.h"

#define SOPC_CUSTOM2_NS_INDEX 2

#include "sopc_types.h"

#include "custom_types.h"

#ifndef OPCUA_EXCLUDE_Custom2_Custom2DataType
/*============================================================================
 * The Custom2_Custom2DataType structure.
 *===========================================================================*/
extern SOPC_EncodeableType OpcUa_Custom2_Custom2DataType_EncodeableType;

typedef struct _OpcUa_Custom2_Custom2DataType
{
    SOPC_EncodeableType* encodeableType;
    /* IMPORTANT NOTE: response header IN RESPONSE MSG BODY is kept only
     *  for giving a copy of the header to application.
     */
    SOPC_Boolean fieldb;
    uint16_t fieldu;
} OpcUa_Custom2_Custom2DataType;

void OpcUa_Custom2_Custom2DataType_Initialize(void* pValue);

void OpcUa_Custom2_Custom2DataType_Clear(void* pValue);

#endif

#ifndef OPCUA_EXCLUDE_Custom2_CustomWithNS1DataType
/*============================================================================
 * The Custom2_CustomWithNS1DataType structure.
 *===========================================================================*/
extern SOPC_EncodeableType OpcUa_Custom2_CustomWithNS1DataType_EncodeableType;

typedef struct _OpcUa_Custom2_CustomWithNS1DataType
{
    SOPC_EncodeableType* encodeableType;
    /* IMPORTANT NOTE: response header IN RESPONSE MSG BODY is kept only
     *  for giving a copy of the header to application.
     */
    OpcUa_Custom2_Custom2DataType custom2;
    OpcUa_Custom_CustomWithNS0DataType custom1;
} OpcUa_Custom2_CustomWithNS1DataType;

void OpcUa_Custom2_CustomWithNS1DataType_Initialize(void* pValue);

void OpcUa_Custom2_CustomWithNS1DataType_Clear(void* pValue);

#endif

/*============================================================================
 * Indexes in the table of known encodeable types.
 *
 * The enumerated values are indexes in the sopc_Custom2_KnownEncodeableTypes array.
 *===========================================================================*/
typedef enum _SOPC_Custom2_TypeInternalIndex
{
#ifndef OPCUA_EXCLUDE_Custom2_Custom2DataType
    SOPC_TypeInternalIndex_Custom2_Custom2DataType,
#endif
#ifndef OPCUA_EXCLUDE_Custom2_CustomWithNS1DataType
    SOPC_TypeInternalIndex_Custom2_CustomWithNS1DataType,
#endif
    SOPC_Custom2_TypeInternalIndex_SIZE
} SOPC_Custom2_TypeInternalIndex;

/*============================================================================
 * Table of known types.
 *===========================================================================*/
extern SOPC_EncodeableType** sopc_Custom2_KnownEncodeableTypes;

#endif
/* This is the last line of an autogenerated file. */
