/*
 * Licensed to Systerel under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Systerel licenses this file to you under the Apache
 * License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include "custom_types.h"
#include "opcua_S2OPC_identifiers.h"
#include "sopc_encoder.h"

/* DO NOT EDIT. THIS FILE IS GENERATED BY THE SCRIPT gen-sopc-types.py */

/*============================================================================
 * Table of known types.
 *===========================================================================*/
static SOPC_EncodeableType* g_S2OPC_KnownEncodeableTypes[SOPC_S2OPC_TypeInternalIndex_SIZE + 1] = {
#ifndef OPCUA_EXCLUDE_S2OPC_CustomDataType
    &OpcUa_S2OPC_CustomDataType_EncodeableType,
#endif
#ifndef OPCUA_EXCLUDE_S2OPC_CustomDataType2
    &OpcUa_S2OPC_CustomDataType2_EncodeableType,
#endif
    NULL};

/*============================================================================
 * Encodeable types descriptions
 *===========================================================================*/

#ifndef OPCUA_EXCLUDE_S2OPC_CustomDataType
/*============================================================================
 * OpcUa_S2OPC_CustomDataType_Initialize
 *===========================================================================*/
void OpcUa_S2OPC_CustomDataType_Initialize(void* pValue)
{
    SOPC_EncodeableObject_Initialize(&OpcUa_S2OPC_CustomDataType_EncodeableType, pValue);
}

/*============================================================================
 * OpcUa_S2OPC_CustomDataType_Clear
 *===========================================================================*/
void OpcUa_S2OPC_CustomDataType_Clear(void* pValue)
{
    SOPC_EncodeableObject_Clear(&OpcUa_S2OPC_CustomDataType_EncodeableType, pValue);
}

/*============================================================================
 * Field descriptors of the S2OPC_CustomDataType encodeable type.
 *===========================================================================*/
static const SOPC_EncodeableType_FieldDescriptor S2OPC_CustomDataType_Fields[] = {
    {
        true,                                                   // isBuiltIn
        false,                                                  // isArrayLength
        true,                                                   // isToEncode
        (uint32_t) SOPC_Boolean_Id,                             // typeIndex
        (uint32_t) offsetof(OpcUa_S2OPC_CustomDataType, fieldb) // offset
    },
    {
        true,                                                   // isBuiltIn
        false,                                                  // isArrayLength
        true,                                                   // isToEncode
        (uint32_t) SOPC_UInt16_Id,                              // typeIndex
        (uint32_t) offsetof(OpcUa_S2OPC_CustomDataType, fieldu) // offset
    },
};

/*============================================================================
 * Descriptor of the S2OPC_CustomDataType encodeable type.
 *===========================================================================*/
SOPC_EncodeableType OpcUa_S2OPC_CustomDataType_EncodeableType = {
    "S2OPC_CustomDataType",
    OpcUaId_S2OPC_CustomDataType,
    OpcUaId_S2OPC_CustomDataType_Encoding_DefaultBinary,
    OpcUaId_S2OPC_CustomDataType_Encoding_DefaultXml,
    NULL,
    1,
    sizeof(OpcUa_S2OPC_CustomDataType),
    OpcUa_S2OPC_CustomDataType_Initialize,
    OpcUa_S2OPC_CustomDataType_Clear,
    sizeof S2OPC_CustomDataType_Fields / sizeof(SOPC_EncodeableType_FieldDescriptor),
    S2OPC_CustomDataType_Fields,
    g_S2OPC_KnownEncodeableTypes};
#endif

#ifndef OPCUA_EXCLUDE_S2OPC_CustomDataType2
/*============================================================================
 * OpcUa_S2OPC_CustomDataType2_Initialize
 *===========================================================================*/
void OpcUa_S2OPC_CustomDataType2_Initialize(void* pValue)
{
    SOPC_EncodeableObject_Initialize(&OpcUa_S2OPC_CustomDataType2_EncodeableType, pValue);
}

/*============================================================================
 * OpcUa_S2OPC_CustomDataType2_Clear
 *===========================================================================*/
void OpcUa_S2OPC_CustomDataType2_Clear(void* pValue)
{
    SOPC_EncodeableObject_Clear(&OpcUa_S2OPC_CustomDataType2_EncodeableType, pValue);
}

/*============================================================================
 * Field descriptors of the S2OPC_CustomDataType2 encodeable type.
 *===========================================================================*/
static const SOPC_EncodeableType_FieldDescriptor S2OPC_CustomDataType2_Fields[] = {
    {
        true,                                                    // isBuiltIn
        false,                                                   // isArrayLength
        true,                                                    // isToEncode
        (uint32_t) SOPC_Boolean_Id,                              // typeIndex
        (uint32_t) offsetof(OpcUa_S2OPC_CustomDataType2, fieldb) // offset
    },
    {
        false,                                                     // isBuiltIn
        false,                                                     // isArrayLength
        true,                                                      // isToEncode
        (uint32_t) SOPC_TypeInternalIndex_S2OPC_CustomDataType,    // typeIndex
        (uint32_t) offsetof(OpcUa_S2OPC_CustomDataType2, fieldcdt) // offset
    },
};

/*============================================================================
 * Descriptor of the S2OPC_CustomDataType2 encodeable type.
 *===========================================================================*/
SOPC_EncodeableType OpcUa_S2OPC_CustomDataType2_EncodeableType = {
    "S2OPC_CustomDataType2",
    OpcUaId_S2OPC_CustomDataType2,
    OpcUaId_S2OPC_CustomDataType2_Encoding_DefaultBinary,
    OpcUaId_S2OPC_CustomDataType2_Encoding_DefaultXml,
    NULL,
    1,
    sizeof(OpcUa_S2OPC_CustomDataType2),
    OpcUa_S2OPC_CustomDataType2_Initialize,
    OpcUa_S2OPC_CustomDataType2_Clear,
    sizeof S2OPC_CustomDataType2_Fields / sizeof(SOPC_EncodeableType_FieldDescriptor),
    S2OPC_CustomDataType2_Fields,
    g_S2OPC_KnownEncodeableTypes};
#endif

SOPC_EncodeableType** sopc_S2OPC_KnownEncodeableTypes = g_S2OPC_KnownEncodeableTypes;

/* This is the last line of an autogenerated file. */
