/*
 * Licensed to Systerel under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Systerel licenses this file to you under the Apache
 * License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include "custom2_types.h"
#include "opcua_Custom2_identifiers.h"
#include "sopc_encoder.h"

/* DO NOT EDIT. THIS FILE IS GENERATED BY THE SCRIPT gen-sopc-types.py */

/*============================================================================
 * Table of known types.
 *===========================================================================*/
static SOPC_EncodeableType* g_Custom2_KnownEncodeableTypes[SOPC_Custom2_TypeInternalIndex_SIZE + 1] = {
#ifndef OPCUA_EXCLUDE_Custom2_Custom2DataType
    &OpcUa_Custom2_Custom2DataType_EncodeableType,
#endif
#ifndef OPCUA_EXCLUDE_Custom2_CustomWithNS1DataType
    &OpcUa_Custom2_CustomWithNS1DataType_EncodeableType,
#endif
    NULL};

/*============================================================================
 * Encodeable types descriptions
 *===========================================================================*/

#ifndef OPCUA_EXCLUDE_Custom2_Custom2DataType
/*============================================================================
 * OpcUa_Custom2_Custom2DataType_Initialize
 *===========================================================================*/
void OpcUa_Custom2_Custom2DataType_Initialize(void* pValue)
{
    SOPC_EncodeableObject_Initialize(&OpcUa_Custom2_Custom2DataType_EncodeableType, pValue);
}

/*============================================================================
 * OpcUa_Custom2_Custom2DataType_Clear
 *===========================================================================*/
void OpcUa_Custom2_Custom2DataType_Clear(void* pValue)
{
    SOPC_EncodeableObject_Clear(&OpcUa_Custom2_Custom2DataType_EncodeableType, pValue);
}

/*============================================================================
 * Field descriptors of the Custom2_Custom2DataType encodeable type.
 *===========================================================================*/
static const SOPC_EncodeableType_FieldDescriptor Custom2_Custom2DataType_Fields[] = {
    {
        true,                                                      // isBuiltIn
        false,                                                     // isArrayLength
        true,                                                      // isToEncode
        true,                                                      // isSameNs
        (uint16_t) 0,                                              // nsIndex
        (uint32_t) SOPC_Boolean_Id,                                // typeIndex
        (uint32_t) offsetof(OpcUa_Custom2_Custom2DataType, fieldb) // offset
    },
    {
        true,                                                      // isBuiltIn
        false,                                                     // isArrayLength
        true,                                                      // isToEncode
        true,                                                      // isSameNs
        (uint16_t) 0,                                              // nsIndex
        (uint32_t) SOPC_UInt16_Id,                                 // typeIndex
        (uint32_t) offsetof(OpcUa_Custom2_Custom2DataType, fieldu) // offset
    },
};

/*============================================================================
 * Descriptor of the Custom2_Custom2DataType encodeable type.
 *===========================================================================*/
SOPC_EncodeableType OpcUa_Custom2_Custom2DataType_EncodeableType = {
    "Custom2_Custom2DataType",
    OpcUaId_Custom2_Custom2DataType,
    OpcUaId_Custom2_Custom2DataType_Encoding_DefaultBinary,
    OpcUaId_Custom2_Custom2DataType_Encoding_DefaultXml,
    NULL,
    2,
    sizeof(OpcUa_Custom2_Custom2DataType),
    OpcUa_Custom2_Custom2DataType_Initialize,
    OpcUa_Custom2_Custom2DataType_Clear,
    sizeof Custom2_Custom2DataType_Fields / sizeof(SOPC_EncodeableType_FieldDescriptor),
    Custom2_Custom2DataType_Fields,
    g_Custom2_KnownEncodeableTypes};
#endif

#ifndef OPCUA_EXCLUDE_Custom2_CustomWithNS1DataType
/*============================================================================
 * OpcUa_Custom2_CustomWithNS1DataType_Initialize
 *===========================================================================*/
void OpcUa_Custom2_CustomWithNS1DataType_Initialize(void* pValue)
{
    SOPC_EncodeableObject_Initialize(&OpcUa_Custom2_CustomWithNS1DataType_EncodeableType, pValue);
}

/*============================================================================
 * OpcUa_Custom2_CustomWithNS1DataType_Clear
 *===========================================================================*/
void OpcUa_Custom2_CustomWithNS1DataType_Clear(void* pValue)
{
    SOPC_EncodeableObject_Clear(&OpcUa_Custom2_CustomWithNS1DataType_EncodeableType, pValue);
}

/*============================================================================
 * Field descriptors of the Custom2_CustomWithNS1DataType encodeable type.
 *===========================================================================*/
static const SOPC_EncodeableType_FieldDescriptor Custom2_CustomWithNS1DataType_Fields[] = {
    {
        false,                                                            // isBuiltIn
        false,                                                            // isArrayLength
        true,                                                             // isToEncode
        true,                                                             // isSameNs
        (uint16_t) 0,                                                     // nsIndex
        (uint32_t) SOPC_TypeInternalIndex_Custom2_Custom2DataType,        // typeIndex
        (uint32_t) offsetof(OpcUa_Custom2_CustomWithNS1DataType, custom2) // offset
    },
    {
        false,                                                            // isBuiltIn
        false,                                                            // isArrayLength
        true,                                                             // isToEncode
        false,                                                            // isSameNs
        (uint16_t) 1,                                                     // nsIndex
        (uint32_t) SOPC_TypeInternalIndex_Custom_CustomWithNS0DataType,   // typeIndex
        (uint32_t) offsetof(OpcUa_Custom2_CustomWithNS1DataType, custom1) // offset
    },
};

/*============================================================================
 * Descriptor of the Custom2_CustomWithNS1DataType encodeable type.
 *===========================================================================*/
SOPC_EncodeableType OpcUa_Custom2_CustomWithNS1DataType_EncodeableType = {
    "Custom2_CustomWithNS1DataType",
    OpcUaId_Custom2_CustomWithNS1DataType,
    OpcUaId_Custom2_CustomWithNS1DataType_Encoding_DefaultBinary,
    OpcUaId_Custom2_CustomWithNS1DataType_Encoding_DefaultXml,
    NULL,
    2,
    sizeof(OpcUa_Custom2_CustomWithNS1DataType),
    OpcUa_Custom2_CustomWithNS1DataType_Initialize,
    OpcUa_Custom2_CustomWithNS1DataType_Clear,
    sizeof Custom2_CustomWithNS1DataType_Fields / sizeof(SOPC_EncodeableType_FieldDescriptor),
    Custom2_CustomWithNS1DataType_Fields,
    g_Custom2_KnownEncodeableTypes};
#endif

SOPC_EncodeableType** sopc_Custom2_KnownEncodeableTypes = g_Custom2_KnownEncodeableTypes;

/* This is the last line of an autogenerated file. */
