/*
 * Licensed to Systerel under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Systerel licenses this file to you under the Apache
 * License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include "custom_types.h"
#include "opcua_Custom_identifiers.h"
#include "sopc_encoder.h"

/* DO NOT EDIT. THIS FILE IS GENERATED BY THE SCRIPT gen-sopc-types.py */

/*============================================================================
 * Table of known types.
 *===========================================================================*/
static SOPC_EncodeableType* g_Custom_KnownEncodeableTypes[SOPC_Custom_TypeInternalIndex_SIZE + 1] = {
#ifndef OPCUA_EXCLUDE_Custom_CustomDataType
    &OpcUa_Custom_CustomDataType_EncodeableType,
#endif
#ifndef OPCUA_EXCLUDE_Custom_CustomDataType2
    &OpcUa_Custom_CustomDataType2_EncodeableType,
#endif
#ifndef OPCUA_EXCLUDE_Custom_CustomWithNS0DataType
    &OpcUa_Custom_CustomWithNS0DataType_EncodeableType,
#endif
#ifndef OPCUA_EXCLUDE_Custom_CustomUnionDataType
    &OpcUa_Custom_CustomUnionDataType_EncodeableType,
#endif
#ifndef OPCUA_EXCLUDE_Custom_CustomOptFieldsDataType
    &OpcUa_Custom_CustomOptFieldsDataType_EncodeableType,
#endif
    NULL};

/*============================================================================
 * Encodeable types descriptions
 *===========================================================================*/

#ifndef OPCUA_EXCLUDE_Custom_CustomDataType
/*============================================================================
 * OpcUa_Custom_CustomDataType_Initialize
 *===========================================================================*/
void OpcUa_Custom_CustomDataType_Initialize(void* pValue)
{
    SOPC_EncodeableObject_Initialize(&OpcUa_Custom_CustomDataType_EncodeableType, pValue);
}

/*============================================================================
 * OpcUa_Custom_CustomDataType_Clear
 *===========================================================================*/
void OpcUa_Custom_CustomDataType_Clear(void* pValue)
{
    SOPC_EncodeableObject_Clear(&OpcUa_Custom_CustomDataType_EncodeableType, pValue);
}

/*============================================================================
 * Field descriptors of the Custom_CustomDataType encodeable type.
 *===========================================================================*/
static const SOPC_EncodeableType_FieldDescriptor Custom_CustomDataType_Fields[] = {
    {
        false,                                                   // isOptional
        true,                                                    // isBuiltIn
        false,                                                   // isArrayLength
        true,                                                    // isToEncode
        true,                                                    // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                          // nsIndex
        (uint32_t) SOPC_Boolean_Id,                              // typeIndex
        (uint32_t) offsetof(OpcUa_Custom_CustomDataType, fieldb) // offset
    },
    {
        false,                                                   // isOptional
        true,                                                    // isBuiltIn
        false,                                                   // isArrayLength
        true,                                                    // isToEncode
        true,                                                    // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                          // nsIndex
        (uint32_t) SOPC_UInt16_Id,                               // typeIndex
        (uint32_t) offsetof(OpcUa_Custom_CustomDataType, fieldu) // offset
    },
};

/*============================================================================
 * Descriptor of the Custom_CustomDataType encodeable type.
 *===========================================================================*/
SOPC_EncodeableType OpcUa_Custom_CustomDataType_EncodeableType = {
    "Custom_CustomDataType",
    OpcUaId_Custom_CustomDataType,
    OpcUaId_Custom_CustomDataType_Encoding_DefaultBinary,
    OpcUaId_Custom_CustomDataType_Encoding_DefaultXml,
    NULL,
    SOPC_CUSTOM_NS_INDEX,
    sizeof(OpcUa_Custom_CustomDataType),
    OpcUa_Custom_CustomDataType_Initialize,
    OpcUa_Custom_CustomDataType_Clear,
    SOPC_STRUCT_TYPE_CLASSIC,
    sizeof Custom_CustomDataType_Fields / sizeof(SOPC_EncodeableType_FieldDescriptor),
    Custom_CustomDataType_Fields,
    g_Custom_KnownEncodeableTypes};
#endif

#ifndef OPCUA_EXCLUDE_Custom_CustomDataType2
/*============================================================================
 * OpcUa_Custom_CustomDataType2_Initialize
 *===========================================================================*/
void OpcUa_Custom_CustomDataType2_Initialize(void* pValue)
{
    SOPC_EncodeableObject_Initialize(&OpcUa_Custom_CustomDataType2_EncodeableType, pValue);
}

/*============================================================================
 * OpcUa_Custom_CustomDataType2_Clear
 *===========================================================================*/
void OpcUa_Custom_CustomDataType2_Clear(void* pValue)
{
    SOPC_EncodeableObject_Clear(&OpcUa_Custom_CustomDataType2_EncodeableType, pValue);
}

/*============================================================================
 * Field descriptors of the Custom_CustomDataType2 encodeable type.
 *===========================================================================*/
static const SOPC_EncodeableType_FieldDescriptor Custom_CustomDataType2_Fields[] = {
    {
        false,                                                    // isOptional
        true,                                                     // isBuiltIn
        false,                                                    // isArrayLength
        true,                                                     // isToEncode
        true,                                                     // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                           // nsIndex
        (uint32_t) SOPC_Boolean_Id,                               // typeIndex
        (uint32_t) offsetof(OpcUa_Custom_CustomDataType2, fieldb) // offset
    },
    {
        false,                                                      // isOptional
        false,                                                      // isBuiltIn
        false,                                                      // isArrayLength
        true,                                                       // isToEncode
        true,                                                       // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                             // nsIndex
        (uint32_t) SOPC_TypeInternalIndex_Custom_CustomDataType,    // typeIndex
        (uint32_t) offsetof(OpcUa_Custom_CustomDataType2, fieldcdt) // offset
    },
};

/*============================================================================
 * Descriptor of the Custom_CustomDataType2 encodeable type.
 *===========================================================================*/
SOPC_EncodeableType OpcUa_Custom_CustomDataType2_EncodeableType = {
    "Custom_CustomDataType2",
    OpcUaId_Custom_CustomDataType2,
    OpcUaId_Custom_CustomDataType2_Encoding_DefaultBinary,
    OpcUaId_Custom_CustomDataType2_Encoding_DefaultXml,
    NULL,
    SOPC_CUSTOM_NS_INDEX,
    sizeof(OpcUa_Custom_CustomDataType2),
    OpcUa_Custom_CustomDataType2_Initialize,
    OpcUa_Custom_CustomDataType2_Clear,
    SOPC_STRUCT_TYPE_CLASSIC,
    sizeof Custom_CustomDataType2_Fields / sizeof(SOPC_EncodeableType_FieldDescriptor),
    Custom_CustomDataType2_Fields,
    g_Custom_KnownEncodeableTypes};
#endif

#ifndef OPCUA_EXCLUDE_Custom_CustomWithNS0DataType
/*============================================================================
 * OpcUa_Custom_CustomWithNS0DataType_Initialize
 *===========================================================================*/
void OpcUa_Custom_CustomWithNS0DataType_Initialize(void* pValue)
{
    SOPC_EncodeableObject_Initialize(&OpcUa_Custom_CustomWithNS0DataType_EncodeableType, pValue);
}

/*============================================================================
 * OpcUa_Custom_CustomWithNS0DataType_Clear
 *===========================================================================*/
void OpcUa_Custom_CustomWithNS0DataType_Clear(void* pValue)
{
    SOPC_EncodeableObject_Clear(&OpcUa_Custom_CustomWithNS0DataType_EncodeableType, pValue);
}

/*============================================================================
 * Field descriptors of the Custom_CustomWithNS0DataType encodeable type.
 *===========================================================================*/
static const SOPC_EncodeableType_FieldDescriptor Custom_CustomWithNS0DataType_Fields[] = {
    {
        false,                                                          // isOptional
        true,                                                           // isBuiltIn
        false,                                                          // isArrayLength
        true,                                                           // isToEncode
        true,                                                           // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                 // nsIndex
        (uint32_t) SOPC_Boolean_Id,                                     // typeIndex
        (uint32_t) offsetof(OpcUa_Custom_CustomWithNS0DataType, fieldb) // offset
    },
    {
        false,                                                           // isOptional
        false,                                                           // isBuiltIn
        false,                                                           // isArrayLength
        true,                                                            // isToEncode
        false,                                                           // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                  // nsIndex
        (uint32_t) SOPC_TypeInternalIndex_KeyValuePair,                  // typeIndex
        (uint32_t) offsetof(OpcUa_Custom_CustomWithNS0DataType, keyPair) // offset
    },
};

/*============================================================================
 * Descriptor of the Custom_CustomWithNS0DataType encodeable type.
 *===========================================================================*/
SOPC_EncodeableType OpcUa_Custom_CustomWithNS0DataType_EncodeableType = {
    "Custom_CustomWithNS0DataType",
    OpcUaId_Custom_CustomWithNS0DataType,
    OpcUaId_Custom_CustomWithNS0DataType_Encoding_DefaultBinary,
    OpcUaId_Custom_CustomWithNS0DataType_Encoding_DefaultXml,
    NULL,
    SOPC_CUSTOM_NS_INDEX,
    sizeof(OpcUa_Custom_CustomWithNS0DataType),
    OpcUa_Custom_CustomWithNS0DataType_Initialize,
    OpcUa_Custom_CustomWithNS0DataType_Clear,
    SOPC_STRUCT_TYPE_CLASSIC,
    sizeof Custom_CustomWithNS0DataType_Fields / sizeof(SOPC_EncodeableType_FieldDescriptor),
    Custom_CustomWithNS0DataType_Fields,
    g_Custom_KnownEncodeableTypes};
#endif

#ifndef OPCUA_EXCLUDE_Custom_CustomUnionDataType
/*============================================================================
 * OpcUa_Custom_CustomUnionDataType_Initialize
 *===========================================================================*/
void OpcUa_Custom_CustomUnionDataType_Initialize(void* pValue)
{
    SOPC_EncodeableObject_Initialize(&OpcUa_Custom_CustomUnionDataType_EncodeableType, pValue);
}

/*============================================================================
 * OpcUa_Custom_CustomUnionDataType_Clear
 *===========================================================================*/
void OpcUa_Custom_CustomUnionDataType_Clear(void* pValue)
{
    SOPC_EncodeableObject_Clear(&OpcUa_Custom_CustomUnionDataType_EncodeableType, pValue);
}

/*============================================================================
 * Field descriptors of the Custom_CustomUnionDataType encodeable type.
 *===========================================================================*/
static const SOPC_EncodeableType_FieldDescriptor Custom_CustomUnionDataType_Fields[] = {
    {
        false,                                                             // isOptional
        true,                                                              // isBuiltIn
        false,                                                             // isArrayLength
        true,                                                              // isToEncode
        true,                                                              // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                    // nsIndex
        (uint32_t) SOPC_UInt32_Id,                                         // typeIndex
        (uint32_t) offsetof(OpcUa_Custom_CustomUnionDataType, SwitchField) // offset
    },
    {
        false,                                                                 // isOptional
        true,                                                                  // isBuiltIn
        false,                                                                 // isArrayLength
        true,                                                                  // isToEncode
        true,                                                                  // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                        // nsIndex
        (uint32_t) SOPC_Boolean_Id,                                            // typeIndex
        (uint32_t) offsetof(OpcUa_Custom_CustomUnionDataType, Value.FieldBool) // offset
    },
    {
        false,                                                                   // isOptional
        true,                                                                    // isBuiltIn
        false,                                                                   // isArrayLength
        true,                                                                    // isToEncode
        true,                                                                    // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                          // nsIndex
        (uint32_t) SOPC_UInt16_Id,                                               // typeIndex
        (uint32_t) offsetof(OpcUa_Custom_CustomUnionDataType, Value.FieldUint16) // offset
    },
};

/*============================================================================
 * Descriptor of the Custom_CustomUnionDataType encodeable type.
 *===========================================================================*/
SOPC_EncodeableType OpcUa_Custom_CustomUnionDataType_EncodeableType = {
    "Custom_CustomUnionDataType",
    OpcUaId_Custom_CustomUnionDataType,
    OpcUaId_Custom_CustomUnionDataType_Encoding_DefaultBinary,
    OpcUaId_Custom_CustomUnionDataType_Encoding_DefaultXml,
    NULL,
    SOPC_CUSTOM_NS_INDEX,
    sizeof(OpcUa_Custom_CustomUnionDataType),
    OpcUa_Custom_CustomUnionDataType_Initialize,
    OpcUa_Custom_CustomUnionDataType_Clear,
    SOPC_STRUCT_TYPE_UNION,
    sizeof Custom_CustomUnionDataType_Fields / sizeof(SOPC_EncodeableType_FieldDescriptor),
    Custom_CustomUnionDataType_Fields,
    g_Custom_KnownEncodeableTypes};
#endif

#ifndef OPCUA_EXCLUDE_Custom_CustomOptFieldsDataType
/*============================================================================
 * OpcUa_Custom_CustomOptFieldsDataType_Initialize
 *===========================================================================*/
void OpcUa_Custom_CustomOptFieldsDataType_Initialize(void* pValue)
{
    SOPC_EncodeableObject_Initialize(&OpcUa_Custom_CustomOptFieldsDataType_EncodeableType, pValue);
}

/*============================================================================
 * OpcUa_Custom_CustomOptFieldsDataType_Clear
 *===========================================================================*/
void OpcUa_Custom_CustomOptFieldsDataType_Clear(void* pValue)
{
    SOPC_EncodeableObject_Clear(&OpcUa_Custom_CustomOptFieldsDataType_EncodeableType, pValue);
}

/*============================================================================
 * Field descriptors of the Custom_CustomOptFieldsDataType encodeable type.
 *===========================================================================*/
static const SOPC_EncodeableType_FieldDescriptor Custom_CustomOptFieldsDataType_Fields[] = {
    {
        false,                                                               // isOptional
        true,                                                                // isBuiltIn
        false,                                                               // isArrayLength
        true,                                                                // isToEncode
        true,                                                                // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                      // nsIndex
        (uint32_t) SOPC_Boolean_Id,                                          // typeIndex
        (uint32_t) offsetof(OpcUa_Custom_CustomOptFieldsDataType, FieldBool) // offset
    },
    {
        false,                                                                   // isOptional
        true,                                                                    // isBuiltIn
        false,                                                                   // isArrayLength
        true,                                                                    // isToEncode
        true,                                                                    // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                          // nsIndex
        (uint32_t) SOPC_UInt32_Id,                                               // typeIndex
        (uint32_t) offsetof(OpcUa_Custom_CustomOptFieldsDataType, FieldUint32_1) // offset
    },
    {
        true,                                                                    // isOptional
        true,                                                                    // isBuiltIn
        false,                                                                   // isArrayLength
        true,                                                                    // isToEncode
        true,                                                                    // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                          // nsIndex
        (uint32_t) SOPC_UInt32_Id,                                               // typeIndex
        (uint32_t) offsetof(OpcUa_Custom_CustomOptFieldsDataType, FieldUint32_2) // offset
    },
    {
        true,                                                                    // isOptional
        true,                                                                    // isBuiltIn
        false,                                                                   // isArrayLength
        true,                                                                    // isToEncode
        true,                                                                    // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                          // nsIndex
        (uint32_t) SOPC_UInt32_Id,                                               // typeIndex
        (uint32_t) offsetof(OpcUa_Custom_CustomOptFieldsDataType, FieldUint32_3) // offset
    },
    {
        true,                                                                      // isOptional
        true,                                                                      // isBuiltIn
        true,                                                                      // isArrayLength
        true,                                                                      // isToEncode
        true,                                                                      // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                            // nsIndex
        (uint32_t) SOPC_Int32_Id,                                                  // typeIndex
        (uint32_t) offsetof(OpcUa_Custom_CustomOptFieldsDataType, NoOfArrayUint16) // offset
    },
    {
        true,                                                                  // isOptional
        true,                                                                  // isBuiltIn
        false,                                                                 // isArrayLength
        true,                                                                  // isToEncode
        true,                                                                  // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                        // nsIndex
        (uint32_t) SOPC_UInt16_Id,                                             // typeIndex
        (uint32_t) offsetof(OpcUa_Custom_CustomOptFieldsDataType, ArrayUint16) // offset
    },
    {
        true,                                                               // isOptional
        false,                                                              // isBuiltIn
        false,                                                              // isArrayLength
        true,                                                               // isToEncode
        true,                                                               // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                     // nsIndex
        (uint32_t) SOPC_TypeInternalIndex_Custom_CustomDataType,            // typeIndex
        (uint32_t) offsetof(OpcUa_Custom_CustomOptFieldsDataType, Fieldcdt) // offset
    },
};

/*============================================================================
 * Descriptor of the Custom_CustomOptFieldsDataType encodeable type.
 *===========================================================================*/
SOPC_EncodeableType OpcUa_Custom_CustomOptFieldsDataType_EncodeableType = {
    "Custom_CustomOptFieldsDataType",
    OpcUaId_Custom_CustomOptFieldsDataType,
    OpcUaId_Custom_CustomOptFieldsDataType_Encoding_DefaultBinary,
    OpcUaId_Custom_CustomOptFieldsDataType_Encoding_DefaultXml,
    NULL,
    SOPC_CUSTOM_NS_INDEX,
    sizeof(OpcUa_Custom_CustomOptFieldsDataType),
    OpcUa_Custom_CustomOptFieldsDataType_Initialize,
    OpcUa_Custom_CustomOptFieldsDataType_Clear,
    SOPC_STRUCT_TYPE_OPT_FIELDS,
    sizeof Custom_CustomOptFieldsDataType_Fields / sizeof(SOPC_EncodeableType_FieldDescriptor),
    Custom_CustomOptFieldsDataType_Fields,
    g_Custom_KnownEncodeableTypes};
#endif

SOPC_EncodeableType** sopc_Custom_KnownEncodeableTypes = g_Custom_KnownEncodeableTypes;

/* This is the last line of an autogenerated file. */
