/* Copyright (C) Systerel SAS 2019, all rights reserved. */

#include "pubsub_config_static.h"

#include <stdbool.h>
#include <string.h>

#include "sopc_assert.h"

// DO NOT EDIT THIS FILE HAS BEEN GENERATED BY generate-s2opc_pubsub-static-config.py



static SOPC_WriterGroup* SOPC_PubSubConfig_SetPubMessageAt(SOPC_PubSubConnection* connection,
                                                           uint16_t index,
                                                           uint16_t groupId,
                                                           uint32_t groupVersion,
                                                           double interval,
                                                           int32_t offsetUs,
                                                           SOPC_SecurityMode_Type securityMode,
                                                           const char * topic)
{
    SOPC_WriterGroup* group = SOPC_PubSubConnection_Get_WriterGroup_At(connection, index);
    SOPC_WriterGroup_Set_Id(group, groupId);
    SOPC_WriterGroup_Set_Version(group, groupVersion);
    SOPC_WriterGroup_Set_PublishingInterval(group, interval);
    SOPC_WriterGroup_Set_SecurityMode(group, securityMode);
    if (NULL != topic)
    {
    	SOPC_WriterGroup_Set_MqttTopic(group, topic);
    }
    if (offsetUs >=0)
    {
        SOPC_WriterGroup_Set_PublishingOffset(group, offsetUs / 1000);
    }

    return group;
}



static SOPC_PublishedDataSet* SOPC_PubSubConfig_InitDataSet(SOPC_PubSubConfiguration* config,
                                                            uint16_t dataSetIndex,
                                                            SOPC_DataSetWriter* writer,
                                                            bool isAcyclic,
                                                            uint16_t dataSetId,
                                                            uint16_t nbVar)
{
    SOPC_PublishedDataSet* dataset = SOPC_PubSubConfiguration_Get_PublishedDataSet_At(config, dataSetIndex);
    if(isAcyclic)
    {
        SOPC_PublishedDataSet_Init(dataset, SOPC_PublishedDataSetCustomSourceDataType, nbVar);
    }
    else
    {
        SOPC_PublishedDataSet_Init(dataset, SOPC_PublishedDataItemsDataType, nbVar);
    }
    SOPC_DataSetWriter_Set_DataSet(writer, dataset);
    SOPC_DataSetWriter_Set_Id(writer, dataSetId);

    return dataset;
}


static void SOPC_PubSubConfig_SetPubVariableAt(SOPC_PublishedDataSet* dataset,
                                               uint16_t index,
                                               char* strNodeId,
                                               SOPC_BuiltinId builtinType)
{
    SOPC_FieldMetaData* fieldmetadata = SOPC_PublishedDataSet_Get_FieldMetaData_At(dataset, index);
    SOPC_FieldMetaData_Set_ValueRank(fieldmetadata, -1);
    SOPC_FieldMetaData_Set_BuiltinType(fieldmetadata, builtinType);
    SOPC_PublishedVariable* publishedVar = SOPC_FieldMetaData_Get_PublishedVariable(fieldmetadata);
    SOPC_ASSERT(NULL != publishedVar);
    SOPC_NodeId* nodeId = SOPC_NodeId_FromCString(strNodeId, (int32_t) strlen(strNodeId));
    SOPC_ASSERT(NULL != nodeId);
    SOPC_PublishedVariable_Set_NodeId(publishedVar, nodeId);
    SOPC_PublishedVariable_Set_AttributeId(publishedVar,
                                           13); // Value => AttributeId=13
}


static SOPC_ReaderGroup* SOPC_PubSubConfig_SetSubMessageAt(SOPC_PubSubConnection* connection,
                                                           uint16_t index,
                                                           SOPC_SecurityMode_Type securityMode,
                                                           uint16_t groupId,
                                                           uint32_t groupVersion,
                                                           uint32_t publisherId,
                                                           uint16_t nbDataSets)
{
    SOPC_ReaderGroup* readerGroup = SOPC_PubSubConnection_Get_ReaderGroup_At(connection, index);
    SOPC_ASSERT(readerGroup != NULL);
    SOPC_ReaderGroup_Set_SecurityMode(readerGroup, securityMode);
    SOPC_ReaderGroup_Set_GroupVersion(readerGroup, groupVersion);
    SOPC_ReaderGroup_Set_GroupId(readerGroup, groupId);
    SOPC_ReaderGroup_Set_PublisherId_UInteger(readerGroup, publisherId);
    SOPC_ASSERT(nbDataSets < 0x100);
    bool allocSuccess = SOPC_ReaderGroup_Allocate_DataSetReader_Array(readerGroup, (uint8_t) nbDataSets);
    SOPC_ASSERT(allocSuccess);
    
    return readerGroup;
}


static SOPC_DataSetReader* SOPC_PubSubConfig_SetReaderAt(SOPC_ReaderGroup* readerGroup,
                                                         uint16_t index,
                                                         uint16_t writerId,
                                                         double interval,
							 const char * topic)
{
    SOPC_ASSERT(index < 0x100);
    SOPC_DataSetReader* reader = SOPC_ReaderGroup_Get_DataSetReader_At(readerGroup, (uint8_t) index);
    SOPC_ASSERT(reader != NULL);
    SOPC_DataSetReader_Set_DataSetWriterId(reader, writerId);
    SOPC_DataSetReader_Set_ReceiveTimeout(reader, 2.0 * interval);
    if (NULL != topic)
    {
    	SOPC_DataSetReader_Set_MqttTopic(reader,topic);
    }
    return reader;
}


static bool SOPC_PubSubConfig_SetSubNbVariables(SOPC_DataSetReader* reader, uint16_t nbVar)
{
    return SOPC_DataSetReader_Allocate_FieldMetaData_Array(reader, SOPC_TargetVariablesDataType, nbVar);
}


static void SOPC_PubSubConfig_SetSubVariableAt(SOPC_DataSetReader* reader,
                                               uint16_t index,
                                               char* strNodeId,
                                               SOPC_BuiltinId builtinType)
{
    SOPC_FieldMetaData* fieldmetadata = SOPC_DataSetReader_Get_FieldMetaData_At(reader, index);
    SOPC_ASSERT(fieldmetadata != NULL);

    /* fieldmetadata: type the field */
    SOPC_FieldMetaData_Set_ValueRank(fieldmetadata, -1);
    SOPC_FieldMetaData_Set_BuiltinType(fieldmetadata, builtinType);

    /* FieldTarget: link to the source/target data */
    SOPC_FieldTarget* fieldTarget = SOPC_FieldMetaData_Get_TargetVariable(fieldmetadata);
    SOPC_ASSERT(fieldTarget != NULL);
    SOPC_NodeId* nodeId = SOPC_NodeId_FromCString(strNodeId, (int32_t) strlen(strNodeId));
    SOPC_FieldTarget_Set_NodeId(fieldTarget, nodeId);
    SOPC_FieldTarget_Set_AttributeId(fieldTarget, 13); // Value => AttributeId=13
}

SOPC_PubSubConfiguration* SOPC_PubSubConfig_GetStatic(void)
{
    bool alloc = true;
    SOPC_PubSubConfiguration* config = SOPC_PubSubConfiguration_Create();
    
    SOPC_PubSubConnection* connection = NULL;

    /* 1 publisher connection */
    alloc = SOPC_PubSubConfiguration_Allocate_PubConnection_Array(config, 1);
    
    /* 2 Published Datasets */
    alloc = SOPC_PubSubConfiguration_Allocate_PublishedDataSet_Array(config, 2);
    
    /** Publisher connection 0 **/
    
    if (alloc)
    {
        // Set publisher id and address
        connection = SOPC_PubSubConfiguration_Get_PubConnection_At(config, 0);
        SOPC_ASSERT(NULL != connection);
        SOPC_PubSubConnection_Set_PublisherId_UInteger(connection, 123);
        alloc = SOPC_PubSubConnection_Set_Address(connection, "mqtts://192.168.1.108:1883");
    }
    
    // Set acyclic publisher mode
    SOPC_PubSubConnection_Set_AcyclicPublisher(connection, 0);
    
    if (alloc)
    {
        // Allocate 2 writer groups (messages)
        alloc = SOPC_PubSubConnection_Allocate_WriterGroup_Array(connection, 2);
    }

    
    if (alloc)
    {
        // Set MQTT Username and Password
        alloc = SOPC_PubSubConnection_Set_MqttUsername(connection, "user1");
        alloc = SOPC_PubSubConnection_Set_MqttPassword(connection, "password");
    }
    
    SOPC_WriterGroup* writerGroup = NULL;
    /*** Pub Message 14 ***/
    
    if (alloc)
    {
        // GroupId = 14
        // GroupVersion = 1
        // Interval = 2000.000000 ms
        // Offest = -1 us
        // topic = S2OPC
 
       	writerGroup = SOPC_PubSubConfig_SetPubMessageAt(connection, 0, 14, 1, 2000.000000,-1, SOPC_SecurityMode_None,"S2OPC");
       	alloc = NULL != writerGroup;
    	}
 	
    if (alloc)
    {
       // 1 data sets for message 14
       alloc = SOPC_WriterGroup_Allocate_DataSetWriter_Array(writerGroup, 1);
    }

    
    /*** DataSetMessage No 1 of message 14 ***/
    
    SOPC_DataSetWriter* writer = NULL;
    SOPC_PublishedDataSet* dataset = NULL;
    if (alloc)
    {
        writer = SOPC_WriterGroup_Get_DataSetWriter_At(writerGroup, 0);
        SOPC_ASSERT(NULL != writer);
        // WriterId = 51
        dataset = SOPC_PubSubConfig_InitDataSet(config, 0, writer, 0, 51, 1);
        alloc = NULL != dataset;
    }
    if (alloc)
    {
        SOPC_PubSubConfig_SetPubVariableAt(dataset, 0, "ns=2;i=6", SOPC_Float_Id); // PubFloat
    }
    
    /*** Pub Message 15 ***/
    
    if (alloc)
    {
        // GroupId = 15
        // GroupVersion = 1
        // Interval = 1000.000000 ms
        // Offest = -1 us
        // topic = mqtt_topic
 
       	writerGroup = SOPC_PubSubConfig_SetPubMessageAt(connection, 1, 15, 1, 1000.000000,-1, SOPC_SecurityMode_None,"mqtt_topic");
       	alloc = NULL != writerGroup;
    	}
 	
    if (alloc)
    {
       // 1 data sets for message 15
       alloc = SOPC_WriterGroup_Allocate_DataSetWriter_Array(writerGroup, 1);
    }

    
    /*** DataSetMessage No 1 of message 15 ***/
    
    if (alloc)
    {
        writer = SOPC_WriterGroup_Get_DataSetWriter_At(writerGroup, 0);
        SOPC_ASSERT(NULL != writer);
        // WriterId = 52
        dataset = SOPC_PubSubConfig_InitDataSet(config, 1, writer, 0, 52, 1);
        alloc = NULL != dataset;
    }
    if (alloc)
    {
        SOPC_PubSubConfig_SetPubVariableAt(dataset, 0, "ns=2;i=7", SOPC_Float_Id); // PubFloat
    }
    

    /* 1 connection Sub */
    alloc = SOPC_PubSubConfiguration_Allocate_SubConnection_Array(config, 1);
    
    /** Subscriber connection 0 **/
    
    if (alloc)
    {
        // Set subscriber id and address
        connection = SOPC_PubSubConfiguration_Get_SubConnection_At(config, 0);
        alloc = SOPC_PubSubConnection_Set_Address(connection, "mqtts://192.168.1.108:1883");
    }

    if (alloc)
    {
        // 2 sub messages
        alloc = SOPC_PubSubConnection_Allocate_ReaderGroup_Array(connection, 2);
    }

        
    SOPC_DataSetReader* dsReader = NULL;
    SOPC_ReaderGroup* readerGroup = NULL;
    /*** Sub Message 14 ***/
    
    if (alloc)
    {
        // Allocate 1 datasets
        // GroupId = 14
        // GroupVersion = 1
        // PubId = 42
        readerGroup = SOPC_PubSubConfig_SetSubMessageAt(connection, 0, SOPC_SecurityMode_None, 14, 1, 42, 1);
        alloc = NULL != readerGroup;
    }
    
    /*** DataSetMessage No 1 of message 14 ***/
    
    if (alloc)
    {
        // Interval = 100.000000 ms
        dsReader = SOPC_PubSubConfig_SetReaderAt(readerGroup, 0, 0, 100.000000, "S2OPC1");
        alloc = NULL != dsReader;
    }
    
    if (alloc)
    {
        alloc = SOPC_PubSubConfig_SetSubNbVariables(dsReader, 2);

    }

    if (alloc)
    {
    
        SOPC_PubSubConfig_SetSubVariableAt(dsReader, 0, "ns=1;s=SubBool", SOPC_Boolean_Id); // varBool
        SOPC_PubSubConfig_SetSubVariableAt(dsReader, 1, "ns=1;s=SubString", SOPC_String_Id); // varString
    }
    
    /*** Sub Message 15 ***/
    
    if (alloc)
    {
        // Allocate 1 datasets
        // GroupId = 15
        // GroupVersion = 1
        // PubId = 42
        readerGroup = SOPC_PubSubConfig_SetSubMessageAt(connection, 1, SOPC_SecurityMode_None, 15, 1, 42, 1);
        alloc = NULL != readerGroup;
    }
    
    /*** DataSetMessage No 1 of message 15 ***/
    
    if (alloc)
    {
        // Interval = 1000.000000 ms
        dsReader = SOPC_PubSubConfig_SetReaderAt(readerGroup, 0, 0, 1000.000000, "test1");
        alloc = NULL != dsReader;
    }
    
    if (alloc)
    {
        alloc = SOPC_PubSubConfig_SetSubNbVariables(dsReader, 2);

    }

    if (alloc)
    {
    
        SOPC_PubSubConfig_SetSubVariableAt(dsReader, 0, "ns=1;s=SubInt", SOPC_Int64_Id); // varInt
        SOPC_PubSubConfig_SetSubVariableAt(dsReader, 1, "ns=1;s=SubUInt", SOPC_UInt64_Id); // varUInt
    }
    

    if (!alloc)
    {
        SOPC_PubSubConfiguration_Delete(config);
        return NULL;
    }

    return config;
}
    
