/*
 * Licensed to Systerel under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Systerel licenses this file to you under the Apache
 * License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include "pubsub_config_static.h"

#include <stdbool.h>
#include <string.h>

#include "sopc_assert.h"

// DO NOT EDIT THIS FILE HAS BEEN GENERATED BY generate-s2opc_pubsub-static-config.py

static SOPC_WriterGroup* SOPC_PubSubConfig_SetPubMessageAt(SOPC_PubSubConnection* connection,
                                                           uint16_t index,
                                                           uint16_t groupId,
                                                           uint32_t groupVersion,
                                                           double interval,
                                                           int32_t offsetUs,
                                                           SOPC_SecurityMode_Type securityMode,
                                                           const char* mqttTopic,
                                                           const SOPC_Pubsub_MessageEncodingType encoding,
                                                           const bool isFixedBufferSize)
{
    SOPC_WriterGroup* group = SOPC_PubSubConnection_Get_WriterGroup_At(connection, index);
    SOPC_WriterGroup_Set_Id(group, groupId);
    SOPC_WriterGroup_Set_Version(group, groupVersion);
    SOPC_WriterGroup_Set_PublishingInterval(group, interval);
    SOPC_WriterGroup_Set_SecurityMode(group, securityMode);
    SOPC_WriterGroup_Set_MqttTopic(group, mqttTopic);
    SOPC_WriterGroup_Set_Encoding(group, encoding);
    const SOPC_WriterGroup_Options writerGroupOptions = {.useFixedSizeBuffer = isFixedBufferSize};
    SOPC_WriterGroup_Set_Options(group, &writerGroupOptions);
    if (offsetUs >= 0)
    {
        SOPC_WriterGroup_Set_PublishingOffset(group, offsetUs / 1000);
    }

    return group;
}

static SOPC_PublishedDataSet* SOPC_PubSubConfig_InitDataSet(SOPC_PubSubConfiguration* config,
                                                            uint16_t dataSetIndex,
                                                            SOPC_DataSetWriter* writer,
                                                            bool isAcyclic,
                                                            uint16_t dataSetId,
                                                            bool useSeqNum,
                                                            bool useTimestamp,
                                                            uint16_t nbVar)
{
    SOPC_PublishedDataSet* dataset = SOPC_PubSubConfiguration_Get_PublishedDataSet_At(config, dataSetIndex);
    if (isAcyclic)
    {
        SOPC_PublishedDataSet_Init(dataset, SOPC_PublishedDataSetCustomSourceDataType, nbVar);
    }
    else
    {
        SOPC_PublishedDataSet_Init(dataset, SOPC_PublishedDataItemsDataType, nbVar);
    }
    SOPC_DataSetWriter_Set_DataSet(writer, dataset);
    SOPC_DataSetWriter_Set_Id(writer, dataSetId);
    const SOPC_DataSetWriter_Options dsmOptions = {.noUseSeqNum = !useSeqNum, .noTimestamp = !useTimestamp};
    SOPC_DataSetWriter_Set_Options(writer, &dsmOptions);

    return dataset;
}

static void SOPC_PubSubConfig_SetPubVariableAt(SOPC_PublishedDataSet* dataset,
                                               uint16_t index,
                                               const char* strNodeId,
                                               SOPC_BuiltinId builtinType,
                                               int32_t valueRank,
                                               uint32_t* arrayDimensions)
{
    SOPC_FieldMetaData* fieldmetadata = SOPC_PublishedDataSet_Get_FieldMetaData_At(dataset, index);
    SOPC_PubSub_ArrayDimension arrayDimension = {.valueRank = valueRank, .arrayDimensions = arrayDimensions};
    SOPC_FieldMetaDeta_SetCopy_ArrayDimension(fieldmetadata, &arrayDimension);
    SOPC_FieldMetaData_Set_BuiltinType(fieldmetadata, builtinType);
    SOPC_PublishedVariable* publishedVar = SOPC_FieldMetaData_Get_PublishedVariable(fieldmetadata);
    SOPC_ASSERT(NULL != publishedVar);
    SOPC_NodeId* nodeId = SOPC_NodeId_FromCString(strNodeId, (int32_t) strlen(strNodeId));
    SOPC_ASSERT(NULL != nodeId);
    SOPC_PublishedVariable_Set_NodeId(publishedVar, nodeId);
    SOPC_PublishedVariable_Set_AttributeId(publishedVar,
                                           13); // Value => AttributeId=13
}

static SOPC_ReaderGroup* SOPC_PubSubConfig_SetSubMessageAt(SOPC_PubSubConnection* connection,
                                                           uint16_t index,
                                                           SOPC_SecurityMode_Type securityMode,
                                                           uint16_t groupId,
                                                           uint32_t groupVersion,
                                                           SOPC_Conf_PublisherId publisherId,
                                                           uint16_t nbDataSets,
                                                           const char* mqttTopic)
{
    SOPC_ReaderGroup* readerGroup = SOPC_PubSubConnection_Get_ReaderGroup_At(connection, index);
    SOPC_ASSERT(readerGroup != NULL);
    SOPC_ReaderGroup_Set_SecurityMode(readerGroup, securityMode);
    SOPC_ReaderGroup_Set_GroupVersion(readerGroup, groupVersion);
    SOPC_ReaderGroup_Set_GroupId(readerGroup, groupId);
    SOPC_ASSERT(nbDataSets < 0x100);
    bool allocSuccess = SOPC_ReaderGroup_Allocate_DataSetReader_Array(readerGroup, (uint8_t) nbDataSets);
    SOPC_ASSERT(allocSuccess);
    SOPC_ReaderGroup_Set_MqttTopic(readerGroup, mqttTopic);
    if (SOPC_UInteger_PublisherId == publisherId.type)
    {
        SOPC_ReaderGroup_Set_PublisherId_UInteger(readerGroup, publisherId.data.uint);
    }
    else
    {
        SOPC_ReaderGroup_Set_PublisherId_String(readerGroup, &publisherId.data.string);
    }
    return readerGroup;
}

static SOPC_DataSetReader* SOPC_PubSubConfig_SetReaderAt(SOPC_ReaderGroup* readerGroup,
                                                         uint16_t index,
                                                         uint16_t writerId,
                                                         double interval)
{
    SOPC_ASSERT(index < 0x100);
    SOPC_DataSetReader* reader = SOPC_ReaderGroup_Get_DataSetReader_At(readerGroup, (uint8_t) index);
    SOPC_ASSERT(reader != NULL);
    SOPC_DataSetReader_Set_DataSetWriterId(reader, writerId);
    SOPC_DataSetReader_Set_ReceiveTimeout(reader, 2.0 * interval);
    return reader;
}

static bool SOPC_PubSubConfig_SetSubNbVariables(SOPC_DataSetReader* reader, uint16_t nbVar)
{
    return SOPC_DataSetReader_Allocate_FieldMetaData_Array(reader, SOPC_TargetVariablesDataType, nbVar);
}

static void SOPC_PubSubConfig_SetSubVariableAt(SOPC_DataSetReader* reader,
                                               uint16_t index,
                                               const char* strNodeId,
                                               SOPC_BuiltinId builtinType,
                                               int32_t valueRank,
                                               uint32_t* arrayDimensions)
{
    SOPC_FieldMetaData* fieldmetadata = SOPC_DataSetReader_Get_FieldMetaData_At(reader, index);
    SOPC_ASSERT(fieldmetadata != NULL);

    /* fieldmetadata: type the field */
    SOPC_FieldMetaData_Set_BuiltinType(fieldmetadata, builtinType);
    SOPC_PubSub_ArrayDimension arrayDimension = {.valueRank = valueRank, .arrayDimensions = arrayDimensions};
    SOPC_FieldMetaDeta_SetCopy_ArrayDimension(fieldmetadata, &arrayDimension);
    /* FieldTarget: link to the source/target data */
    SOPC_FieldTarget* fieldTarget = SOPC_FieldMetaData_Get_TargetVariable(fieldmetadata);
    SOPC_ASSERT(fieldTarget != NULL);
    SOPC_NodeId* nodeId = SOPC_NodeId_FromCString(strNodeId, (int32_t) strlen(strNodeId));
    SOPC_FieldTarget_Set_NodeId(fieldTarget, nodeId);
    SOPC_FieldTarget_Set_AttributeId(fieldTarget, 13); // Value => AttributeId=13
}

SOPC_PubSubConfiguration* SOPC_PubSubConfig_GetStatic(void)
{
    bool alloc = true;
    SOPC_PubSubConfiguration* config = SOPC_PubSubConfiguration_Create();

    SOPC_PubSubConnection* connection = NULL;

    /* 1 publisher connection */
    alloc = SOPC_PubSubConfiguration_Allocate_PubConnection_Array(config, 1);

    /* 3 Published Datasets */
    alloc = SOPC_PubSubConfiguration_Allocate_PublishedDataSet_Array(config, 3);

    /** Publisher connection 0 **/

    if (alloc)
    {
        // Set address
        connection = SOPC_PubSubConfiguration_Get_PubConnection_At(config, 0);
        SOPC_ASSERT(NULL != connection);
        alloc = SOPC_PubSubConnection_Set_Address(connection, "opc.udp://232.1.2.100:4840");
    }

    if (alloc)
    {
        // Set publisher id
        SOPC_PubSubConnection_Set_PublisherId_UInteger(connection, 123);
    }

    // Set acyclic publisher mode
    SOPC_PubSubConnection_Set_AcyclicPublisher(connection, 0);

    if (alloc)
    {
        // Allocate 2 writer groups (messages)
        alloc = SOPC_PubSubConnection_Allocate_WriterGroup_Array(connection, 2);
    }

    SOPC_WriterGroup* writerGroup = NULL;
    /*** Pub Message 14 ***/

    if (alloc)
    {
        // GroupId = 14
        // GroupVersion = 1
        // Interval = 200.000000 ms
        // Offest = -1 us
        // mqttTopic = NULL
        // encoding = SOPC_MessageEncodeUADP
        writerGroup = SOPC_PubSubConfig_SetPubMessageAt(connection, 0, 14, 1, 200.000000, -1, SOPC_SecurityMode_None,
                                                        NULL, SOPC_MessageEncodeUADP, 0);
        alloc = NULL != writerGroup;
    }

    if (alloc)
    {
        // 2 data sets for message 14
        alloc = SOPC_WriterGroup_Allocate_DataSetWriter_Array(writerGroup, 2);
    }

    /*** DataSetMessage No 1 of message 14 ***/

    SOPC_DataSetWriter* writer = NULL;
    SOPC_PublishedDataSet* dataset = NULL;
    if (alloc)
    {
        writer = SOPC_WriterGroup_Get_DataSetWriter_At(writerGroup, 0);
        SOPC_ASSERT(NULL != writer);
        // WriterId = 50
        dataset = SOPC_PubSubConfig_InitDataSet(config, 0, writer, 0, 50, 1, 0, 1);
        alloc = NULL != dataset;
    }
    if (alloc)
    {
        SOPC_PubSubConfig_SetPubVariableAt(dataset, 0, "ns=1;i=5", SOPC_Boolean_Id, -1, NULL); // PubBool
    }

    /*** DataSetMessage No 2 of message 14 ***/

    if (alloc)
    {
        writer = SOPC_WriterGroup_Get_DataSetWriter_At(writerGroup, 1);
        SOPC_ASSERT(NULL != writer);
        // WriterId = 51
        dataset = SOPC_PubSubConfig_InitDataSet(config, 1, writer, 0, 51, 1, 0, 2);
        alloc = NULL != dataset;
    }
    if (alloc)
    {
        SOPC_PubSubConfig_SetPubVariableAt(dataset, 0, "ns=1;i=6", SOPC_UInt32_Id, -1, NULL); // PubUInt32
        SOPC_PubSubConfig_SetPubVariableAt(dataset, 1, "ns=1;i=2", SOPC_Int16_Id, -1, NULL);  // PubInt16
    }

    /*** Pub Message 15 ***/

    if (alloc)
    {
        // GroupId = 15
        // GroupVersion = 1
        // Interval = 100.000000 ms
        // Offest = -1 us
        // mqttTopic = NULL
        // encoding = SOPC_MessageEncodeUADP
        writerGroup = SOPC_PubSubConfig_SetPubMessageAt(connection, 1, 15, 1, 100.000000, -1, SOPC_SecurityMode_None,
                                                        NULL, SOPC_MessageEncodeUADP, 0);
        alloc = NULL != writerGroup;
    }

    if (alloc)
    {
        // 1 data sets for message 15
        alloc = SOPC_WriterGroup_Allocate_DataSetWriter_Array(writerGroup, 1);
    }

    /*** DataSetMessage No 1 of message 15 ***/

    if (alloc)
    {
        writer = SOPC_WriterGroup_Get_DataSetWriter_At(writerGroup, 0);
        SOPC_ASSERT(NULL != writer);
        // WriterId = 52
        dataset = SOPC_PubSubConfig_InitDataSet(config, 2, writer, 0, 52, 1, 0, 1);
        alloc = NULL != dataset;
    }
    if (alloc)
    {
        SOPC_PubSubConfig_SetPubVariableAt(dataset, 0, "ns=1;i=3", SOPC_Float_Id, -1, NULL); // PubFloat
    }

    /* 1 connection Sub */
    alloc = SOPC_PubSubConfiguration_Allocate_SubConnection_Array(config, 1);

    /** Subscriber connection 0 **/

    if (alloc)
    {
        // Set subscriber id and address
        connection = SOPC_PubSubConfiguration_Get_SubConnection_At(config, 0);
        alloc = SOPC_PubSubConnection_Set_Address(connection, "opc.udp://232.1.2.100:4840");
    }

    if (alloc)
    {
        // 1 sub messages
        alloc = SOPC_PubSubConnection_Allocate_ReaderGroup_Array(connection, 1);
    }

    SOPC_DataSetReader* dsReader = NULL;
    SOPC_ReaderGroup* readerGroup = NULL;
    /*** Sub Message 14 ***/

    if (alloc)
    {
        // Allocate 2 datasets
        // GroupId = 14
        // GroupVersion = 1
        // PubId = 123
        // mqttTopic = NULL
        SOPC_Conf_PublisherId pubId = {.type = SOPC_UInteger_PublisherId, .data.uint = 123};
        readerGroup = SOPC_PubSubConfig_SetSubMessageAt(connection, 0, SOPC_SecurityMode_None, 14, 1, pubId, 2, NULL);
        alloc = NULL != readerGroup;
    }

    /*** DataSetMessage No 1 of message 14 ***/

    if (alloc)
    {
        // Interval = 200.000000 ms
        dsReader = SOPC_PubSubConfig_SetReaderAt(readerGroup, 0, 50, 200.000000);
        alloc = NULL != dsReader;
    }

    if (alloc)
    {
        alloc = SOPC_PubSubConfig_SetSubNbVariables(dsReader, 1);
    }

    if (alloc)
    {
        SOPC_PubSubConfig_SetSubVariableAt(dsReader, 0, "ns=1;i=5", SOPC_Boolean_Id, -1, NULL); // SubBool
    }

    /*** DataSetMessage No 2 of message 14 ***/

    if (alloc)
    {
        // Interval = 200.000000 ms
        dsReader = SOPC_PubSubConfig_SetReaderAt(readerGroup, 1, 51, 200.000000);
        alloc = NULL != dsReader;
    }

    if (alloc)
    {
        alloc = SOPC_PubSubConfig_SetSubNbVariables(dsReader, 2);
    }

    if (alloc)
    {
        SOPC_PubSubConfig_SetSubVariableAt(dsReader, 0, "ns=1;i=6", SOPC_UInt32_Id, -1, NULL); // SubUInt32
        SOPC_PubSubConfig_SetSubVariableAt(dsReader, 1, "ns=1;i=2", SOPC_Int16_Id, -1, NULL);  // SubInt16
    }

    if (!alloc)
    {
        SOPC_PubSubConfiguration_Delete(config);
        return NULL;
    }

    return config;
}
