# Licensed to Systerel under one or more contributor license
# agreements. See the NOTICE file distributed with this work
# for additional information regarding copyright ownership.
# Systerel licenses this file to you under the Apache
# License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License. You may obtain
# a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Directory to respectively S2OPC and MbedTLS project
#MBEDTLS_PRJ_DIR = ./mbedtls-2.28.1
#S2OPC_PRJ_DIR = ./S2OPC

UNIT_TEST_DIR = ${S2OPC_PRJ_DIR}/pikeos/unit_test
VALIDATION_TEST_DIR = ${S2OPC_PRJ_DIR}/pikeos/validation_test
MBEDTLS_CONFIG_USER_DIR = ${S2OPC_PRJ_DIR}/pikeos/common/mbedtls

-include ${UNIT_TEST_DIR}/../makefiles_libgen/makefileMbedtlsUserConfig.defs
-include ${UNIT_TEST_DIR}/../makefiles_libgen/makefileMbedtls.defs
-include ${UNIT_TEST_DIR}/../makefiles_libgen/makefileCommon.defs
-include ${UNIT_TEST_DIR}/../makefiles_libgen/makefileClientServer.defs
-include ${UNIT_TEST_DIR}/../makefiles_libgen/makefileAddspaceLoader.defs
-include ${UNIT_TEST_DIR}/../makefiles_libgen/makefilePubSub.defs

CPPFLAGS += -I${UNIT_TEST_DIR}/../common -I$(MBEDTLS_CONFIG_USER_DIR)

UNIT_TEST_OBJ = unit_test time threads sockets atomic mem_alloc
CHECK_UNIT_TEST_OBJ = check_sockets check_threads
VALIDATION_TEST_OBJ = toolkit_test_server_client toolkit_test_publisher_subscriber pubsub_config_static ../server/address_space

MBEDTLS_USER_CUSTOM_OBJ = p_entropy_source p_time_mbedtls

MODLIST = $(MBEDTLS_MODLIST) $(S2OPC_MODLISTPUBSUB) $(S2OPC_MODLISTCLIENTSERVER) $(S2OPC_MODLISTCOMMON) $(S2OPC_MODLISTADDSPACE) $(S2OPC_MODLISTTIME) \
			$(addprefix $(UNIT_TEST_DIR)/,$(UNIT_TEST_OBJ)) \
            $(addprefix $(UNIT_TEST_DIR)/check_tests/,$(CHECK_UNIT_TEST_OBJ)) \
            $(addprefix $(VALIDATION_TEST_DIR)/,$(VALIDATION_TEST_OBJ)) \
			$(addprefix $(MBEDTLS_CONFIG_USER_DIR)/,$(MBEDTLS_USER_CUSTOM_OBJ))

APPLIST = unit_test.elf

# Discard Warning on generated files
$(ODIR)/${VALIDATION_TEST_DIR}/../server/address_space.o: ${VALIDATION_TEST_DIR}/../server/address_space.c $(MAKEFILE_LIST)
	@test -d "$(@D)" || mkdir -p "$(@D)"
ifneq ($(PIKEOS_COMPILATION_DEPENDENCY),false)
	@test -d "$(DEPDIR)/$(*D)" || mkdir -p "$(DEPDIR)/$(*D)"
endif
ifneq ($(ARTIFACT_FLAGS_C),)
	$(CC) $(ARTIFACT_FLAGS_C) -Wno-cast-qual -Wno-missing-field-initializers -o $@ $<
else
	$(call run_cmd,CC $@,$(CC) $(CPPFLAGS) $(CFLAGS) -Wno-cast-qual -Wno-missing-field-initializers  $(DEP_FLAGS) -o $@ -c $<)
endif

$(APPLIST): $(addprefix $(ODIR)/, $(addsuffix .o, $(MODLIST)))
