/*
 * Licensed to Systerel under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Systerel licenses this file to you under the Apache
 * License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include "fx_ac_types.h"
#include "opcua_FX_AC_identifiers.h"
#include "sopc_encoder.h"

/* DO NOT EDIT. THIS FILE IS GENERATED BY THE SCRIPT gen-sopc-types.py */

/*============================================================================
 * Table of known types.
 *===========================================================================*/
static SOPC_EncodeableType* g_FX_AC_KnownEncodeableTypes[SOPC_FX_AC_TypeInternalIndex_SIZE + 1] = {
#ifndef OPCUA_EXCLUDE_FX_AC_AggregatedHealthDataType
    &OpcUa_FX_AC_AggregatedHealthDataType_EncodeableType,
#endif
#ifndef OPCUA_EXCLUDE_FX_AC_ApplicationId
    &OpcUa_FX_AC_ApplicationId_EncodeableType,
#endif
#ifndef OPCUA_EXCLUDE_FX_AC_ApplicationIdentifierDataType
    &OpcUa_FX_AC_ApplicationIdentifierDataType_EncodeableType,
#endif
#ifndef OPCUA_EXCLUDE_FX_AC_FxVersion
    &OpcUa_FX_AC_FxVersion_EncodeableType,
#endif
#ifndef OPCUA_EXCLUDE_FX_AC_IntervalRange
    &OpcUa_FX_AC_IntervalRange_EncodeableType,
#endif
#ifndef OPCUA_EXCLUDE_FX_AC_PublisherQosDataType
    &OpcUa_FX_AC_PublisherQosDataType_EncodeableType,
#endif
#ifndef OPCUA_EXCLUDE_FX_AC_SubscriberQosDataType
    &OpcUa_FX_AC_SubscriberQosDataType_EncodeableType,
#endif
    NULL};

/*============================================================================
 * Encodeable types descriptions
 *===========================================================================*/

#ifndef OPCUA_EXCLUDE_FX_AC_AggregatedHealthDataType
/*============================================================================
 * OpcUa_FX_AC_AggregatedHealthDataType_Initialize
 *===========================================================================*/
void OpcUa_FX_AC_AggregatedHealthDataType_Initialize(void* pValue)
{
    SOPC_EncodeableObject_Initialize(&OpcUa_FX_AC_AggregatedHealthDataType_EncodeableType, pValue);
}

/*============================================================================
 * OpcUa_FX_AC_AggregatedHealthDataType_Clear
 *===========================================================================*/
void OpcUa_FX_AC_AggregatedHealthDataType_Clear(void* pValue)
{
    SOPC_EncodeableObject_Clear(&OpcUa_FX_AC_AggregatedHealthDataType_EncodeableType, pValue);
}

/*============================================================================
 * Field descriptors of the FX_AC_AggregatedHealthDataType encodeable type.
 *===========================================================================*/
static const SOPC_EncodeableType_FieldDescriptor FX_AC_AggregatedHealthDataType_Fields[] = {
    {
        false,                                                                            // isOptional
        true,                                                                             // isBuiltIn
        false,                                                                            // isArrayLength
        true,                                                                             // isToEncode
        true,                                                                             // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                                   // nsIndex
        (uint32_t) SOPC_UInt16_Id,                                                        // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_AggregatedHealthDataType, AggregatedDeviceHealth) // offset
    },
    {
        false,                                                                                 // isOptional
        true,                                                                                  // isBuiltIn
        false,                                                                                 // isArrayLength
        true,                                                                                  // isToEncode
        true,                                                                                  // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                                        // nsIndex
        (uint32_t) SOPC_UInt32_Id,                                                             // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_AggregatedHealthDataType, AggregatedOperationalHealth) // offset
    },
};

/*============================================================================
 * Descriptor of the FX_AC_AggregatedHealthDataType encodeable type.
 *===========================================================================*/
SOPC_EncodeableType OpcUa_FX_AC_AggregatedHealthDataType_EncodeableType = {
    "FX_AC_AggregatedHealthDataType",
    OpcUaId_FX_AC_AggregatedHealthDataType,
    OpcUaId_FX_AC_AggregatedHealthDataType_Encoding_DefaultBinary,
    OpcUaId_FX_AC_AggregatedHealthDataType_Encoding_DefaultXml,
    NULL,
    SOPC_FX_AC_NS_INDEX,
    sizeof(OpcUa_FX_AC_AggregatedHealthDataType),
    OpcUa_FX_AC_AggregatedHealthDataType_Initialize,
    OpcUa_FX_AC_AggregatedHealthDataType_Clear,
    SOPC_STRUCT_TYPE_CLASSIC,
    sizeof FX_AC_AggregatedHealthDataType_Fields / sizeof(SOPC_EncodeableType_FieldDescriptor),
    FX_AC_AggregatedHealthDataType_Fields,
    g_FX_AC_KnownEncodeableTypes};
#endif

#ifndef OPCUA_EXCLUDE_FX_AC_ApplicationId
/*============================================================================
 * OpcUa_FX_AC_ApplicationId_Initialize
 *===========================================================================*/
void OpcUa_FX_AC_ApplicationId_Initialize(void* pValue)
{
    SOPC_EncodeableObject_Initialize(&OpcUa_FX_AC_ApplicationId_EncodeableType, pValue);
}

/*============================================================================
 * OpcUa_FX_AC_ApplicationId_Clear
 *===========================================================================*/
void OpcUa_FX_AC_ApplicationId_Clear(void* pValue)
{
    SOPC_EncodeableObject_Clear(&OpcUa_FX_AC_ApplicationId_EncodeableType, pValue);
}

/*============================================================================
 * Field descriptors of the FX_AC_ApplicationId encodeable type.
 *===========================================================================*/
static const SOPC_EncodeableType_FieldDescriptor FX_AC_ApplicationId_Fields[] = {
    {
        false,                                                      // isOptional
        true,                                                       // isBuiltIn
        false,                                                      // isArrayLength
        true,                                                       // isToEncode
        true,                                                       // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                             // nsIndex
        (uint32_t) SOPC_UInt32_Id,                                  // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_ApplicationId, SwitchField) // offset
    },
    {
        false,                                                          // isOptional
        true,                                                           // isBuiltIn
        false,                                                          // isArrayLength
        true,                                                           // isToEncode
        true,                                                           // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                 // nsIndex
        (uint32_t) SOPC_UInt32_Id,                                      // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_ApplicationId, Value.IdNumeric) // offset
    },
    {
        false,                                                         // isOptional
        true,                                                          // isBuiltIn
        false,                                                         // isArrayLength
        true,                                                          // isToEncode
        true,                                                          // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                // nsIndex
        (uint32_t) SOPC_String_Id,                                     // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_ApplicationId, Value.IdString) // offset
    },
    {
        false,                                                       // isOptional
        true,                                                        // isBuiltIn
        false,                                                       // isArrayLength
        true,                                                        // isToEncode
        true,                                                        // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                              // nsIndex
        (uint32_t) SOPC_Guid_Id,                                     // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_ApplicationId, Value.IdGuid) // offset
    },
    {
        false,                                                             // isOptional
        true,                                                              // isBuiltIn
        false,                                                             // isArrayLength
        true,                                                              // isToEncode
        true,                                                              // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                    // nsIndex
        (uint32_t) SOPC_ByteString_Id,                                     // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_ApplicationId, Value.IdByteString) // offset
    },
};

/*============================================================================
 * Descriptor of the FX_AC_ApplicationId encodeable type.
 *===========================================================================*/
SOPC_EncodeableType OpcUa_FX_AC_ApplicationId_EncodeableType = {
    "FX_AC_ApplicationId",
    OpcUaId_FX_AC_ApplicationId,
    OpcUaId_FX_AC_ApplicationId_Encoding_DefaultBinary,
    OpcUaId_FX_AC_ApplicationId_Encoding_DefaultXml,
    NULL,
    SOPC_FX_AC_NS_INDEX,
    sizeof(OpcUa_FX_AC_ApplicationId),
    OpcUa_FX_AC_ApplicationId_Initialize,
    OpcUa_FX_AC_ApplicationId_Clear,
    SOPC_STRUCT_TYPE_UNION,
    sizeof FX_AC_ApplicationId_Fields / sizeof(SOPC_EncodeableType_FieldDescriptor),
    FX_AC_ApplicationId_Fields,
    g_FX_AC_KnownEncodeableTypes};
#endif

#ifndef OPCUA_EXCLUDE_FX_AC_ApplicationIdentifierDataType
/*============================================================================
 * OpcUa_FX_AC_ApplicationIdentifierDataType_Initialize
 *===========================================================================*/
void OpcUa_FX_AC_ApplicationIdentifierDataType_Initialize(void* pValue)
{
    SOPC_EncodeableObject_Initialize(&OpcUa_FX_AC_ApplicationIdentifierDataType_EncodeableType, pValue);
}

/*============================================================================
 * OpcUa_FX_AC_ApplicationIdentifierDataType_Clear
 *===========================================================================*/
void OpcUa_FX_AC_ApplicationIdentifierDataType_Clear(void* pValue)
{
    SOPC_EncodeableObject_Clear(&OpcUa_FX_AC_ApplicationIdentifierDataType_EncodeableType, pValue);
}

/*============================================================================
 * Field descriptors of the FX_AC_ApplicationIdentifierDataType encodeable type.
 *===========================================================================*/
static const SOPC_EncodeableType_FieldDescriptor FX_AC_ApplicationIdentifierDataType_Fields[] = {
    {
        false,                                                               // isOptional
        true,                                                                // isBuiltIn
        false,                                                               // isArrayLength
        true,                                                                // isToEncode
        true,                                                                // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                      // nsIndex
        (uint32_t) SOPC_LocalizedText_Id,                                    // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_ApplicationIdentifierDataType, Name) // offset
    },
    {
        false,                                                                           // isOptional
        false,                                                                           // isBuiltIn
        false,                                                                           // isArrayLength
        true,                                                                            // isToEncode
        true,                                                                            // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                                  // nsIndex
        (uint32_t) SOPC_TypeInternalIndex_FX_AC_ApplicationId,                           // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_ApplicationIdentifierDataType, UniqueIdentifier) // offset
    },
};

/*============================================================================
 * Descriptor of the FX_AC_ApplicationIdentifierDataType encodeable type.
 *===========================================================================*/
SOPC_EncodeableType OpcUa_FX_AC_ApplicationIdentifierDataType_EncodeableType = {
    "FX_AC_ApplicationIdentifierDataType",
    OpcUaId_FX_AC_ApplicationIdentifierDataType,
    OpcUaId_FX_AC_ApplicationIdentifierDataType_Encoding_DefaultBinary,
    OpcUaId_FX_AC_ApplicationIdentifierDataType_Encoding_DefaultXml,
    NULL,
    SOPC_FX_AC_NS_INDEX,
    sizeof(OpcUa_FX_AC_ApplicationIdentifierDataType),
    OpcUa_FX_AC_ApplicationIdentifierDataType_Initialize,
    OpcUa_FX_AC_ApplicationIdentifierDataType_Clear,
    SOPC_STRUCT_TYPE_CLASSIC,
    sizeof FX_AC_ApplicationIdentifierDataType_Fields / sizeof(SOPC_EncodeableType_FieldDescriptor),
    FX_AC_ApplicationIdentifierDataType_Fields,
    g_FX_AC_KnownEncodeableTypes};
#endif

#ifndef OPCUA_EXCLUDE_FX_AC_FxVersion
/*============================================================================
 * OpcUa_FX_AC_FxVersion_Initialize
 *===========================================================================*/
void OpcUa_FX_AC_FxVersion_Initialize(void* pValue)
{
    SOPC_EncodeableObject_Initialize(&OpcUa_FX_AC_FxVersion_EncodeableType, pValue);
}

/*============================================================================
 * OpcUa_FX_AC_FxVersion_Clear
 *===========================================================================*/
void OpcUa_FX_AC_FxVersion_Clear(void* pValue)
{
    SOPC_EncodeableObject_Clear(&OpcUa_FX_AC_FxVersion_EncodeableType, pValue);
}

/*============================================================================
 * Field descriptors of the FX_AC_FxVersion encodeable type.
 *===========================================================================*/
static const SOPC_EncodeableType_FieldDescriptor FX_AC_FxVersion_Fields[] = {
    {
        false,                                            // isOptional
        true,                                             // isBuiltIn
        false,                                            // isArrayLength
        true,                                             // isToEncode
        true,                                             // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                   // nsIndex
        (uint32_t) SOPC_UInt16_Id,                        // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_FxVersion, Major) // offset
    },
    {
        false,                                            // isOptional
        true,                                             // isBuiltIn
        false,                                            // isArrayLength
        true,                                             // isToEncode
        true,                                             // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                   // nsIndex
        (uint32_t) SOPC_UInt16_Id,                        // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_FxVersion, Minor) // offset
    },
    {
        false,                                            // isOptional
        true,                                             // isBuiltIn
        false,                                            // isArrayLength
        true,                                             // isToEncode
        true,                                             // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                   // nsIndex
        (uint32_t) SOPC_UInt16_Id,                        // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_FxVersion, Build) // offset
    },
    {
        false,                                               // isOptional
        true,                                                // isBuiltIn
        false,                                               // isArrayLength
        true,                                                // isToEncode
        true,                                                // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                      // nsIndex
        (uint32_t) SOPC_UInt16_Id,                           // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_FxVersion, SubBuild) // offset
    },
};

/*============================================================================
 * Descriptor of the FX_AC_FxVersion encodeable type.
 *===========================================================================*/
SOPC_EncodeableType OpcUa_FX_AC_FxVersion_EncodeableType = {
    "FX_AC_FxVersion",
    OpcUaId_FX_AC_FxVersion,
    OpcUaId_FX_AC_FxVersion_Encoding_DefaultBinary,
    OpcUaId_FX_AC_FxVersion_Encoding_DefaultXml,
    NULL,
    SOPC_FX_AC_NS_INDEX,
    sizeof(OpcUa_FX_AC_FxVersion),
    OpcUa_FX_AC_FxVersion_Initialize,
    OpcUa_FX_AC_FxVersion_Clear,
    SOPC_STRUCT_TYPE_CLASSIC,
    sizeof FX_AC_FxVersion_Fields / sizeof(SOPC_EncodeableType_FieldDescriptor),
    FX_AC_FxVersion_Fields,
    g_FX_AC_KnownEncodeableTypes};
#endif

#ifndef OPCUA_EXCLUDE_FX_AC_IntervalRange
/*============================================================================
 * OpcUa_FX_AC_IntervalRange_Initialize
 *===========================================================================*/
void OpcUa_FX_AC_IntervalRange_Initialize(void* pValue)
{
    SOPC_EncodeableObject_Initialize(&OpcUa_FX_AC_IntervalRange_EncodeableType, pValue);
}

/*============================================================================
 * OpcUa_FX_AC_IntervalRange_Clear
 *===========================================================================*/
void OpcUa_FX_AC_IntervalRange_Clear(void* pValue)
{
    SOPC_EncodeableObject_Clear(&OpcUa_FX_AC_IntervalRange_EncodeableType, pValue);
}

/*============================================================================
 * Field descriptors of the FX_AC_IntervalRange encodeable type.
 *===========================================================================*/
static const SOPC_EncodeableType_FieldDescriptor FX_AC_IntervalRange_Fields[] = {
    {
        false,                                              // isOptional
        true,                                               // isBuiltIn
        false,                                              // isArrayLength
        true,                                               // isToEncode
        true,                                               // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                     // nsIndex
        (uint32_t) SOPC_UInt32_Id,                          // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_IntervalRange, Min) // offset
    },
    {
        false,                                              // isOptional
        true,                                               // isBuiltIn
        false,                                              // isArrayLength
        true,                                               // isToEncode
        true,                                               // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                     // nsIndex
        (uint32_t) SOPC_UInt32_Id,                          // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_IntervalRange, Max) // offset
    },
    {
        false,                                                    // isOptional
        true,                                                     // isBuiltIn
        false,                                                    // isArrayLength
        true,                                                     // isToEncode
        true,                                                     // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                           // nsIndex
        (uint32_t) SOPC_UInt16_Id,                                // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_IntervalRange, Increment) // offset
    },
    {
        false,                                                     // isOptional
        true,                                                      // isBuiltIn
        false,                                                     // isArrayLength
        true,                                                      // isToEncode
        true,                                                      // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                            // nsIndex
        (uint32_t) SOPC_UInt16_Id,                                 // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_IntervalRange, Multiplier) // offset
    },
    {
        false,                                               // isOptional
        true,                                                // isBuiltIn
        false,                                               // isArrayLength
        true,                                                // isToEncode
        true,                                                // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                      // nsIndex
        (uint32_t) SOPC_UInt32_Id,                           // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_IntervalRange, Unit) // offset
    },
};

/*============================================================================
 * Descriptor of the FX_AC_IntervalRange encodeable type.
 *===========================================================================*/
SOPC_EncodeableType OpcUa_FX_AC_IntervalRange_EncodeableType = {
    "FX_AC_IntervalRange",
    OpcUaId_FX_AC_IntervalRange,
    OpcUaId_FX_AC_IntervalRange_Encoding_DefaultBinary,
    OpcUaId_FX_AC_IntervalRange_Encoding_DefaultXml,
    NULL,
    SOPC_FX_AC_NS_INDEX,
    sizeof(OpcUa_FX_AC_IntervalRange),
    OpcUa_FX_AC_IntervalRange_Initialize,
    OpcUa_FX_AC_IntervalRange_Clear,
    SOPC_STRUCT_TYPE_CLASSIC,
    sizeof FX_AC_IntervalRange_Fields / sizeof(SOPC_EncodeableType_FieldDescriptor),
    FX_AC_IntervalRange_Fields,
    g_FX_AC_KnownEncodeableTypes};
#endif

#ifndef OPCUA_EXCLUDE_FX_AC_PublisherQosDataType
/*============================================================================
 * OpcUa_FX_AC_PublisherQosDataType_Initialize
 *===========================================================================*/
void OpcUa_FX_AC_PublisherQosDataType_Initialize(void* pValue)
{
    SOPC_EncodeableObject_Initialize(&OpcUa_FX_AC_PublisherQosDataType_EncodeableType, pValue);
}

/*============================================================================
 * OpcUa_FX_AC_PublisherQosDataType_Clear
 *===========================================================================*/
void OpcUa_FX_AC_PublisherQosDataType_Clear(void* pValue)
{
    SOPC_EncodeableObject_Clear(&OpcUa_FX_AC_PublisherQosDataType_EncodeableType, pValue);
}

/*============================================================================
 * Field descriptors of the FX_AC_PublisherQosDataType encodeable type.
 *===========================================================================*/
static const SOPC_EncodeableType_FieldDescriptor FX_AC_PublisherQosDataType_Fields[] = {
    {
        false,                                                             // isOptional
        true,                                                              // isBuiltIn
        false,                                                             // isArrayLength
        true,                                                              // isToEncode
        true,                                                              // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                    // nsIndex
        (uint32_t) SOPC_String_Id,                                         // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_PublisherQosDataType, QosCategory) // offset
    },
    {
        false,                                                                 // isOptional
        true,                                                                  // isBuiltIn
        true,                                                                  // isArrayLength
        true,                                                                  // isToEncode
        true,                                                                  // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                        // nsIndex
        (uint32_t) SOPC_Int32_Id,                                              // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_PublisherQosDataType, NoOfDatagramQos) // offset
    },
    {
        false,                                                             // isOptional
        true,                                                              // isBuiltIn
        false,                                                             // isArrayLength
        true,                                                              // isToEncode
        true,                                                              // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                    // nsIndex
        (uint32_t) SOPC_ExtensionObject_Id,                                // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_PublisherQosDataType, DatagramQos) // offset
    },
};

/*============================================================================
 * Descriptor of the FX_AC_PublisherQosDataType encodeable type.
 *===========================================================================*/
SOPC_EncodeableType OpcUa_FX_AC_PublisherQosDataType_EncodeableType = {
    "FX_AC_PublisherQosDataType",
    OpcUaId_FX_AC_PublisherQosDataType,
    OpcUaId_FX_AC_PublisherQosDataType_Encoding_DefaultBinary,
    OpcUaId_FX_AC_PublisherQosDataType_Encoding_DefaultXml,
    NULL,
    SOPC_FX_AC_NS_INDEX,
    sizeof(OpcUa_FX_AC_PublisherQosDataType),
    OpcUa_FX_AC_PublisherQosDataType_Initialize,
    OpcUa_FX_AC_PublisherQosDataType_Clear,
    SOPC_STRUCT_TYPE_CLASSIC,
    sizeof FX_AC_PublisherQosDataType_Fields / sizeof(SOPC_EncodeableType_FieldDescriptor),
    FX_AC_PublisherQosDataType_Fields,
    g_FX_AC_KnownEncodeableTypes};
#endif

#ifndef OPCUA_EXCLUDE_FX_AC_SubscriberQosDataType
/*============================================================================
 * OpcUa_FX_AC_SubscriberQosDataType_Initialize
 *===========================================================================*/
void OpcUa_FX_AC_SubscriberQosDataType_Initialize(void* pValue)
{
    SOPC_EncodeableObject_Initialize(&OpcUa_FX_AC_SubscriberQosDataType_EncodeableType, pValue);
}

/*============================================================================
 * OpcUa_FX_AC_SubscriberQosDataType_Clear
 *===========================================================================*/
void OpcUa_FX_AC_SubscriberQosDataType_Clear(void* pValue)
{
    SOPC_EncodeableObject_Clear(&OpcUa_FX_AC_SubscriberQosDataType_EncodeableType, pValue);
}

/*============================================================================
 * Field descriptors of the FX_AC_SubscriberQosDataType encodeable type.
 *===========================================================================*/
static const SOPC_EncodeableType_FieldDescriptor FX_AC_SubscriberQosDataType_Fields[] = {
    {
        false,                                                              // isOptional
        true,                                                               // isBuiltIn
        false,                                                              // isArrayLength
        true,                                                               // isToEncode
        true,                                                               // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                     // nsIndex
        (uint32_t) SOPC_String_Id,                                          // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_SubscriberQosDataType, QosCategory) // offset
    },
    {
        false,                                                                  // isOptional
        true,                                                                   // isBuiltIn
        true,                                                                   // isArrayLength
        true,                                                                   // isToEncode
        true,                                                                   // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                         // nsIndex
        (uint32_t) SOPC_Int32_Id,                                               // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_SubscriberQosDataType, NoOfDatagramQos) // offset
    },
    {
        false,                                                              // isOptional
        true,                                                               // isBuiltIn
        false,                                                              // isArrayLength
        true,                                                               // isToEncode
        true,                                                               // isSameNs
        (uint16_t) SOPC_OPCUA_NS_INDEX,                                     // nsIndex
        (uint32_t) SOPC_ExtensionObject_Id,                                 // typeIndex
        (uint32_t) offsetof(OpcUa_FX_AC_SubscriberQosDataType, DatagramQos) // offset
    },
};

/*============================================================================
 * Descriptor of the FX_AC_SubscriberQosDataType encodeable type.
 *===========================================================================*/
SOPC_EncodeableType OpcUa_FX_AC_SubscriberQosDataType_EncodeableType = {
    "FX_AC_SubscriberQosDataType",
    OpcUaId_FX_AC_SubscriberQosDataType,
    OpcUaId_FX_AC_SubscriberQosDataType_Encoding_DefaultBinary,
    OpcUaId_FX_AC_SubscriberQosDataType_Encoding_DefaultXml,
    NULL,
    SOPC_FX_AC_NS_INDEX,
    sizeof(OpcUa_FX_AC_SubscriberQosDataType),
    OpcUa_FX_AC_SubscriberQosDataType_Initialize,
    OpcUa_FX_AC_SubscriberQosDataType_Clear,
    SOPC_STRUCT_TYPE_CLASSIC,
    sizeof FX_AC_SubscriberQosDataType_Fields / sizeof(SOPC_EncodeableType_FieldDescriptor),
    FX_AC_SubscriberQosDataType_Fields,
    g_FX_AC_KnownEncodeableTypes};
#endif

SOPC_EncodeableType** sopc_FX_AC_KnownEncodeableTypes = g_FX_AC_KnownEncodeableTypes;

/* This is the last line of an autogenerated file. */
