/*
 * Licensed to Systerel under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Systerel licenses this file to you under the Apache
 * License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#ifndef SOPC_FX_AC_Enum_Types_H_
#define SOPC_FX_AC_Enum_Types_H_ 1

/* DO NOT EDIT. THIS FILE IS GENERATED BY THE SCRIPT gen-sopc-types.py */

#include <stdint.h>

#ifndef OPCUA_EXCLUDE_FX_AC_ClampKindEnum
/*============================================================================
 * The FX_AC_ClampKindEnum enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_AC_ClampKindEnum
{
    OpcUa_FX_AC_ClampKindEnum_Screw = 0,
    OpcUa_FX_AC_ClampKindEnum_Thumb = 1,
    OpcUa_FX_AC_ClampKindEnum_SizeOf = INT32_MAX
} OpcUa_FX_AC_ClampKindEnum;

#endif

#ifndef OPCUA_EXCLUDE_FX_AC_ConnectionEndpointStatusEnum
/*============================================================================
 * The FX_AC_ConnectionEndpointStatusEnum enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_AC_ConnectionEndpointStatusEnum
{
    OpcUa_FX_AC_ConnectionEndpointStatusEnum_Initial = 0,
    OpcUa_FX_AC_ConnectionEndpointStatusEnum_Ready = 1,
    OpcUa_FX_AC_ConnectionEndpointStatusEnum_PreOperational = 2,
    OpcUa_FX_AC_ConnectionEndpointStatusEnum_Operational = 3,
    OpcUa_FX_AC_ConnectionEndpointStatusEnum_Error = 4,
    OpcUa_FX_AC_ConnectionEndpointStatusEnum_SizeOf = INT32_MAX
} OpcUa_FX_AC_ConnectionEndpointStatusEnum;

#endif

#ifndef OPCUA_EXCLUDE_FX_AC_FxTimeUnitsEnum
/*============================================================================
 * The FX_AC_FxTimeUnitsEnum enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_AC_FxTimeUnitsEnum
{
    OpcUa_FX_AC_FxTimeUnitsEnum_Nanosecond = 0,
    OpcUa_FX_AC_FxTimeUnitsEnum_Microsecond = 1,
    OpcUa_FX_AC_FxTimeUnitsEnum_Millisecond = 2,
    OpcUa_FX_AC_FxTimeUnitsEnum_Second = 3,
    OpcUa_FX_AC_FxTimeUnitsEnum_SizeOf = INT32_MAX
} OpcUa_FX_AC_FxTimeUnitsEnum;

#endif

#ifndef OPCUA_EXCLUDE_FX_AC_SocketKindEnum
/*============================================================================
 * The FX_AC_SocketKindEnum enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_AC_SocketKindEnum
{
    OpcUa_FX_AC_SocketKindEnum_RJ45 = 0,
    OpcUa_FX_AC_SocketKindEnum_M12 = 1,
    OpcUa_FX_AC_SocketKindEnum_SizeOf = INT32_MAX
} OpcUa_FX_AC_SocketKindEnum;

#endif

#ifndef OPCUA_EXCLUDE_FX_AC_CommHealthOptionSet
/*============================================================================
 * The FX_AC_CommHealthOptionSet enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_AC_CommHealthOptionSet
{
    OpcUa_FX_AC_CommHealthOptionSet_CommInitial = 0,
    OpcUa_FX_AC_CommHealthOptionSet_CommPreOperational = 1,
    OpcUa_FX_AC_CommHealthOptionSet_CommError = 2,
    OpcUa_FX_AC_CommHealthOptionSet_SizeOf = UINT16_MAX
} OpcUa_FX_AC_CommHealthOptionSet;

#endif

#ifndef OPCUA_EXCLUDE_FX_AC_DeviceHealthOptionSet
/*============================================================================
 * The FX_AC_DeviceHealthOptionSet enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_AC_DeviceHealthOptionSet
{
    OpcUa_FX_AC_DeviceHealthOptionSet_DeviceFailure = 0,
    OpcUa_FX_AC_DeviceHealthOptionSet_DeviceCheckFunction = 1,
    OpcUa_FX_AC_DeviceHealthOptionSet_DeviceMaintenanceRequired = 2,
    OpcUa_FX_AC_DeviceHealthOptionSet_DeviceOffSpec = 3,
    OpcUa_FX_AC_DeviceHealthOptionSet_SizeOf = UINT16_MAX
} OpcUa_FX_AC_DeviceHealthOptionSet;

#endif

#ifndef OPCUA_EXCLUDE_FX_AC_OperationalHealthOptionSet
/*============================================================================
 * The FX_AC_OperationalHealthOptionSet enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_AC_OperationalHealthOptionSet
{
    OpcUa_FX_AC_OperationalHealthOptionSet_OperationalWarning = 16,
    OpcUa_FX_AC_OperationalHealthOptionSet_OperationalError = 17,
    OpcUa_FX_AC_OperationalHealthOptionSet_SubOperationalWarning = 18,
    OpcUa_FX_AC_OperationalHealthOptionSet_SubOperationalError = 19,
    OpcUa_FX_AC_OperationalHealthOptionSet_SizeOf = INT32_MAX
} OpcUa_FX_AC_OperationalHealthOptionSet;

#endif

#endif
/* This is the last line of an autogenerated file. */
