/*
 * Licensed to Systerel under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Systerel licenses this file to you under the Apache
 * License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#ifndef SOPC_FX_CM_Enum_Types_H_
#define SOPC_FX_CM_Enum_Types_H_ 1

/* DO NOT EDIT. THIS FILE IS GENERATED BY THE SCRIPT gen-sopc-types.py */

#include <stdint.h>

#ifndef OPCUA_EXCLUDE_FX_CM_ConnectionStateEnum
/*============================================================================
 * The FX_CM_ConnectionStateEnum enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_CM_ConnectionStateEnum
{
    OpcUa_FX_CM_ConnectionStateEnum_ConnectionNotMonitored = 0,
    OpcUa_FX_CM_ConnectionStateEnum_ConnectionNotEstablished = 1,
    OpcUa_FX_CM_ConnectionStateEnum_ConnectionInitial = 2,
    OpcUa_FX_CM_ConnectionStateEnum_ConnectionReady = 3,
    OpcUa_FX_CM_ConnectionStateEnum_ConnectionPreOperational = 4,
    OpcUa_FX_CM_ConnectionStateEnum_ConnectionOperational = 5,
    OpcUa_FX_CM_ConnectionStateEnum_ConnectionError = 6,
    OpcUa_FX_CM_ConnectionStateEnum_SizeOf = INT32_MAX
} OpcUa_FX_CM_ConnectionStateEnum;

#endif

#ifndef OPCUA_EXCLUDE_FX_CM_FxEditEnum
/*============================================================================
 * The FX_CM_FxEditEnum enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_CM_FxEditEnum
{
    OpcUa_FX_CM_FxEditEnum_StartEditing = 0,
    OpcUa_FX_CM_FxEditEnum_CommitUpdates = 1,
    OpcUa_FX_CM_FxEditEnum_DiscardUpdates = 2,
    OpcUa_FX_CM_FxEditEnum_SizeOf = INT32_MAX
} OpcUa_FX_CM_FxEditEnum;

#endif

#ifndef OPCUA_EXCLUDE_FX_CM_FxErrorEnum
/*============================================================================
 * The FX_CM_FxErrorEnum enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_CM_FxErrorEnum
{
    OpcUa_FX_CM_FxErrorEnum_NoError = 0,
    OpcUa_FX_CM_FxErrorEnum_UnknownStatus = 1,
    OpcUa_FX_CM_FxErrorEnum_Rollback = 2,
    OpcUa_FX_CM_FxErrorEnum_ProcessingStopped = 3,
    OpcUa_FX_CM_FxErrorEnum_ConnectionConfigurationSetInvalid = 4,
    OpcUa_FX_CM_FxErrorEnum_GdsConnectionError = 5,
    OpcUa_FX_CM_FxErrorEnum_GdsProcessingError = 6,
    OpcUa_FX_CM_FxErrorEnum_AliasNameProcessingError = 7,
    OpcUa_FX_CM_FxErrorEnum_ExternalSksConnectionError = 8,
    OpcUa_FX_CM_FxErrorEnum_ExternalSksProcessingError = 9,
    OpcUa_FX_CM_FxErrorEnum_TargetServerConnectionError = 10,
    OpcUa_FX_CM_FxErrorEnum_ResolvingNamespacesError = 11,
    OpcUa_FX_CM_FxErrorEnum_ResolvingPathsError = 12,
    OpcUa_FX_CM_FxErrorEnum_VerifyAssetError = 13,
    OpcUa_FX_CM_FxErrorEnum_VerifyFunctionalEntityError = 14,
    OpcUa_FX_CM_FxErrorEnum_CreateConnectionEndpointError = 15,
    OpcUa_FX_CM_FxErrorEnum_EstablishControlError = 16,
    OpcUa_FX_CM_FxErrorEnum_SetConfigurationDataError = 17,
    OpcUa_FX_CM_FxErrorEnum_ReassignControlError = 18,
    OpcUa_FX_CM_FxErrorEnum_ReserveCommunicationIdsError = 19,
    OpcUa_FX_CM_FxErrorEnum_SetCommunicationConfigurationError = 20,
    OpcUa_FX_CM_FxErrorEnum_EnableCommunicationError = 21,
    OpcUa_FX_CM_FxErrorEnum_CloseConnectionError = 22,
    OpcUa_FX_CM_FxErrorEnum_LocalSksKeyPushError = 23,
    OpcUa_FX_CM_FxErrorEnum_RuntimeError = 24,
    OpcUa_FX_CM_FxErrorEnum_SizeOf = INT32_MAX
} OpcUa_FX_CM_FxErrorEnum;

#endif

#ifndef OPCUA_EXCLUDE_FX_CM_FxProcessEnum
/*============================================================================
 * The FX_CM_FxProcessEnum enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_CM_FxProcessEnum
{
    OpcUa_FX_CM_FxProcessEnum_ActionEstablishConnectionsEnabled = 0,
    OpcUa_FX_CM_FxProcessEnum_ActionEstablishConnectionsDisabled = 1,
    OpcUa_FX_CM_FxProcessEnum_ActionEstablishConnections = 2,
    OpcUa_FX_CM_FxProcessEnum_ActionRemoveConnections = 3,
    OpcUa_FX_CM_FxProcessEnum_ActionEnableConnections = 4,
    OpcUa_FX_CM_FxProcessEnum_ActionDisableConnections = 5,
    OpcUa_FX_CM_FxProcessEnum_SizeOf = INT32_MAX
} OpcUa_FX_CM_FxProcessEnum;

#endif

#ifndef OPCUA_EXCLUDE_FX_CM_ConnectionConfigurationSetOperation
/*============================================================================
 * The FX_CM_ConnectionConfigurationSetOperation enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_CM_ConnectionConfigurationSetOperation
{
    OpcUa_FX_CM_ConnectionConfigurationSetOperation_ElementAdd = 0,
    OpcUa_FX_CM_ConnectionConfigurationSetOperation_ElementRemove = 1,
    OpcUa_FX_CM_ConnectionConfigurationSetOperation_ElementReplace = 2,
    OpcUa_FX_CM_ConnectionConfigurationSetOperation_SizeOf = UINT8_MAX
} OpcUa_FX_CM_ConnectionConfigurationSetOperation;

#endif

#ifndef OPCUA_EXCLUDE_FX_CM_LastActivityMask
/*============================================================================
 * The FX_CM_LastActivityMask enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_CM_LastActivityMask
{
    OpcUa_FX_CM_LastActivityMask_EstablishEnabled = 0,
    OpcUa_FX_CM_LastActivityMask_EstablishDisabled = 1,
    OpcUa_FX_CM_LastActivityMask_Establish = 2,
    OpcUa_FX_CM_LastActivityMask_Remove = 3,
    OpcUa_FX_CM_LastActivityMask_Enable = 4,
    OpcUa_FX_CM_LastActivityMask_Disable = 5,
    OpcUa_FX_CM_LastActivityMask_Error = 15,
    OpcUa_FX_CM_LastActivityMask_SizeOf = UINT16_MAX
} OpcUa_FX_CM_LastActivityMask;

#endif

#endif
/* This is the last line of an autogenerated file. */
