/*
 * Licensed to Systerel under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Systerel licenses this file to you under the Apache
 * License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#ifndef SOPC_FX_Data_Enum_Types_H_
#define SOPC_FX_Data_Enum_Types_H_ 1

/* DO NOT EDIT. THIS FILE IS GENERATED BY THE SCRIPT gen-sopc-types.py */

#include <stdint.h>

#ifndef OPCUA_EXCLUDE_FX_Data_AssetVerificationModeEnum
/*============================================================================
 * The FX_Data_AssetVerificationModeEnum enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_Data_AssetVerificationModeEnum
{
    OpcUa_FX_Data_AssetVerificationModeEnum_AssetCompatibility = 0,
    OpcUa_FX_Data_AssetVerificationModeEnum_AssetIdentity = 1,
    OpcUa_FX_Data_AssetVerificationModeEnum_AssetIdentityAndCompatibility = 2,
    OpcUa_FX_Data_AssetVerificationModeEnum_SizeOf = INT32_MAX
} OpcUa_FX_Data_AssetVerificationModeEnum;

#endif

#ifndef OPCUA_EXCLUDE_FX_Data_AssetVerificationResultEnum
/*============================================================================
 * The FX_Data_AssetVerificationResultEnum enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_Data_AssetVerificationResultEnum
{
    OpcUa_FX_Data_AssetVerificationResultEnum_NotSet = 0,
    OpcUa_FX_Data_AssetVerificationResultEnum_Match = 1,
    OpcUa_FX_Data_AssetVerificationResultEnum_Compatible = 2,
    OpcUa_FX_Data_AssetVerificationResultEnum_Mismatch = 3,
    OpcUa_FX_Data_AssetVerificationResultEnum_SizeOf = INT32_MAX
} OpcUa_FX_Data_AssetVerificationResultEnum;

#endif

#ifndef OPCUA_EXCLUDE_FX_Data_FunctionalEntityVerificationResultEnum
/*============================================================================
 * The FX_Data_FunctionalEntityVerificationResultEnum enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_Data_FunctionalEntityVerificationResultEnum
{
    OpcUa_FX_Data_FunctionalEntityVerificationResultEnum_NotSet = 0,
    OpcUa_FX_Data_FunctionalEntityVerificationResultEnum_Match = 1,
    OpcUa_FX_Data_FunctionalEntityVerificationResultEnum_Mismatch = 2,
    OpcUa_FX_Data_FunctionalEntityVerificationResultEnum_SizeOf = INT32_MAX
} OpcUa_FX_Data_FunctionalEntityVerificationResultEnum;

#endif

#ifndef OPCUA_EXCLUDE_FX_Data_PubSubConnectionEndpointModeEnum
/*============================================================================
 * The FX_Data_PubSubConnectionEndpointModeEnum enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_Data_PubSubConnectionEndpointModeEnum
{
    OpcUa_FX_Data_PubSubConnectionEndpointModeEnum_PublisherSubscriber = 1,
    OpcUa_FX_Data_PubSubConnectionEndpointModeEnum_Publisher = 2,
    OpcUa_FX_Data_PubSubConnectionEndpointModeEnum_Subscriber = 3,
    OpcUa_FX_Data_PubSubConnectionEndpointModeEnum_SizeOf = INT32_MAX
} OpcUa_FX_Data_PubSubConnectionEndpointModeEnum;

#endif

#ifndef OPCUA_EXCLUDE_FX_Data_FxCommandMask
/*============================================================================
 * The FX_Data_FxCommandMask enumeration.
 *===========================================================================*/
typedef enum _OpcUa_FX_Data_FxCommandMask
{
    OpcUa_FX_Data_FxCommandMask_VerifyAssetCmd = 0,
    OpcUa_FX_Data_FxCommandMask_VerifyFunctionalEntityCmd = 1,
    OpcUa_FX_Data_FxCommandMask_CreateConnectionEndpointCmd = 2,
    OpcUa_FX_Data_FxCommandMask_EstablishControlCmd = 3,
    OpcUa_FX_Data_FxCommandMask_SetConfigurationDataCmd = 4,
    OpcUa_FX_Data_FxCommandMask_ReassignControlCmd = 5,
    OpcUa_FX_Data_FxCommandMask_ReserveCommunicationIdsCmd = 6,
    OpcUa_FX_Data_FxCommandMask_SetCommunicationConfigurationCmd = 7,
    OpcUa_FX_Data_FxCommandMask_EnableCommunicationCmd = 8,
    OpcUa_FX_Data_FxCommandMask_SizeOf = INT32_MAX
} OpcUa_FX_Data_FxCommandMask;

#endif

#endif
/* This is the last line of an autogenerated file. */
