/*
 * Licensed to Systerel under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Systerel licenses this file to you under the Apache
 * License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#ifndef OPCUA_FX_CM_IDENTIFIERS_H
#define OpcUaId_FX_CM_SubscriberConfigurationType 1001
#define OpcUaId_FX_CM_ConnectionManagerType 1002
#define OpcUaId_FX_CM_CommunicationFlowConfigurationType 1003
#define OpcUaId_FX_CM_ConnectionConfigurationSetEventType 1006
#define OpcUaId_FX_CM_ConnectionConfigurationSetProcessingStartedEventType 1007
#define OpcUaId_FX_CM_ConnectionConfigurationSetProcessingSucceededEventType 1008
#define OpcUaId_FX_CM_ConnectionConfigurationSetProcessingFailedEventType 1009
#define OpcUaId_FX_CM_ConnectionManagerCapabilitiesType 1010
#define OpcUaId_FX_CM_ConnectionManagerConfigurationType 1011
#define OpcUaId_FX_CM_ConnectionConfigurationSetType 1012
#define OpcUaId_FX_CM_ConnectionConfigurationType 1013
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType 1014
#define OpcUaId_FX_CM_EstablishConnectionErrorEventType 1015
#define OpcUaId_FX_CM_CommunicationModelConfigurationType 1016
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType 1018
#define OpcUaId_FX_CM_CloseConnectionErrorEventType 1020
#define OpcUaId_FX_CM_PortableKeyValuePair 1035
#define OpcUaId_FX_CM_ServerAddressDataType 1036
#define OpcUaId_FX_CM_PubSubCommunicationModelConfigurationType 1042
#define OpcUaId_FX_CM_PortableRelativePath 1047
#define OpcUaId_FX_CM_PortableRelativePathElement 1051
#define OpcUaId_FX_CM_HasServerAddress 1053
#define OpcUaId_FX_CM_HasConnectionConfiguration 1057
#define OpcUaId_FX_CM_HasCommunicationFlowConfiguration 1060
#define OpcUaId_FX_CM_HasAutomationComponentConfiguration 1062
#define OpcUaId_FX_CM_ToAutomationComponentConfiguration 1063
#define OpcUaId_FX_CM_PortableKeyValuePair_Encoding_DefaultBinary 1114
#define OpcUaId_FX_CM_PortableKeyValuePair_Encoding_DefaultXml 1115
#define OpcUaId_FX_CM_PortableKeyValuePair_Encoding_DefaultJson 1116
#define OpcUaId_FX_CM_ServerAddressDataType_Encoding_DefaultBinary 1117
#define OpcUaId_FX_CM_ServerAddressDataType_Encoding_DefaultXml 1118
#define OpcUaId_FX_CM_ServerAddressDataType_Encoding_DefaultJson 1119
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationType 1129
#define OpcUaId_FX_CM_PortableRelativePath_Encoding_DefaultBinary 1159
#define OpcUaId_FX_CM_PortableRelativePath_Encoding_DefaultXml 1160
#define OpcUaId_FX_CM_PortableRelativePath_Encoding_DefaultJson 1161
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets 1163
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType_Ready 1169
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType_Processing 1170
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType_Error 1171
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType_ReadyToProcessing 1174
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType_ProcessingToReady 1175
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType_ProcessingToError 1176
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType_ErrorToProcessing 1177
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_CommunicationFlow 1202
#define OpcUaId_FX_CM_PortableRelativePathElement_Encoding_DefaultBinary 1222
#define OpcUaId_FX_CM_PortableRelativePathElement_Encoding_DefaultXml 1223
#define OpcUaId_FX_CM_PortableRelativePathElement_Encoding_DefaultJson 1224
#define OpcUaId_FX_CM_AutomationComponentConfigurationType 1246
#define OpcUaId_FX_CM_AssetVerificationType 1247
#define OpcUaId_FX_CM_ConnectionEndpointParameterType 1261
#define OpcUaId_FX_CM_ConnectionManagerType_EditConnectionConfigurationSets_InputArguments 1265
#define OpcUaId_FX_CM_ConnectionManagerType_EditConnectionConfigurationSets_OutputArguments 1267
#define OpcUaId_FX_CM_ConnectionManagerType_ProcessConnectionConfigurationSets_InputArguments 1270
#define OpcUaId_FX_CM_ConnectionManagerType_ProcessConnectionConfigurationSets_OutputArguments 1271
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_RollbackOnError 1272
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType_Ready_StateNumber 1386
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType_Processing_StateNumber 1387
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType_Error_StateNumber 1388
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType_ReadyToProcessing_TransitionNumber 1391
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType_ProcessingToReady_TransitionNumber 1392
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType_ProcessingToError_TransitionNumber 1393
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType_ErrorToProcessing_TransitionNumber 1394
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_Address 1459
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_Address_Selections 1460
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_PublishingInterval 1461
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_PublishingInterval_Selections 1462
#define OpcUaId_FX_CM_ConnectionManagerType_EditConnectionConfigurationSets 1481
#define OpcUaId_FX_CM_ConnectionManagerType_ProcessConnectionConfigurationSets 1483
#define OpcUaId_FX_CM_SecurityKeyServerAddressType 2002
#define OpcUaId_FX_CM_ServerAddressType 2003
#define OpcUaId_FX_CM_FxEditEnum 3001
#define OpcUaId_FX_CM_FxProcessEnum 3002
#define OpcUaId_FX_CM_CommunicationFlowQosDataType 3004
#define OpcUaId_FX_CM_PortableNodeIdentifierValuePair 3005
#define OpcUaId_FX_CM_NodeIdTranslationDataType 3006
#define OpcUaId_FX_CM_ConnectionDiagnosticsDataType 3008
#define OpcUaId_FX_CM_LastActivityMask 3009
#define OpcUaId_FX_CM_ConnectionStateEnum 3011
#define OpcUaId_FX_CM_PortableNodeIdentifier 3012
#define OpcUaId_FX_CM_FxErrorEnum 3015
#define OpcUaId_FX_CM_SecurityKeyServerAddressDataType 3021
#define OpcUaId_FX_CM_ToConnectionEndpointConfiguration 4001
#define OpcUaId_FX_CM_HasCharacteristic 4003
#define OpcUaId_FX_CM_ToFlow 4004
#define OpcUaId_FX_CM_HasAssetToVerify 4005
#define OpcUaId_FX_CM_ToInboundFlow 4006
#define OpcUaId_FX_CM_ToOutboundFlow 4007
#define OpcUaId_FX_CM_HasCMCapability 4008
#define OpcUaId_FX_CM_Server_Namespaces_http___opcfoundation_org_UA_FX_CM_ 5001
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationType_ConnectionEndpoint 5002
#define OpcUaId_FX_CM_FxRoot_ConnectionManager_ConnectionConfigurationSets 5003
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_AutomationComponentConfiguration 5004
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet 5005
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_AutomationComponentConfiguration \
    5006
#define OpcUaId_FX_CM_AutomationComponentConfigurationType_AssetVerification 5007
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint1 5008
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint2 5009
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint1_ConnectionEndpoint 5010
#define OpcUaId_FX_CM_FxRoot_ConnectionManager 5011
#define OpcUaId_FX_CM_PortableNodeIdentifierValuePair_Encoding_DefaultXml 5012
#define OpcUaId_FX_CM_AutomationComponentConfigurationType_CommunicationModelConfig 5013
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint2_ConnectionEndpoint 5014
#define OpcUaId_FX_CM_PortableNodeIdentifierValuePair_Encoding_DefaultJson 5015
#define OpcUaId_FX_CM_PortableNodeIdentifierValuePair_Encoding_DefaultBinary 5016
#define OpcUaId_FX_CM_CommunicationFlowQosDataType_Encoding_DefaultBinary 5017
#define OpcUaId_FX_CM_CommunicationFlowQosDataType_Encoding_DefaultXml 5018
#define OpcUaId_FX_CM_CommunicationFlowQosDataType_Encoding_DefaultJson 5019
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint1_ConnectionEndpoint 5020
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint2_ConnectionEndpoint 5021
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection 5022
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint1 5023
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_SubscriberConfiguration 5024
#define OpcUaId_FX_CM_NodeIdTranslationDataType_Encoding_DefaultBinary 5025
#define OpcUaId_FX_CM_NodeIdTranslationDataType_Encoding_DefaultXml 5026
#define OpcUaId_FX_CM_NodeIdTranslationDataType_Encoding_DefaultJson 5027
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint2 5028
#define OpcUaId_FX_CM_ConnectionConfigurationSetConfDataType_Encoding_DefaultBinary 5029
#define OpcUaId_FX_CM_ConnectionConfigurationSetConfDataType_Encoding_DefaultXml 5030
#define OpcUaId_FX_CM_ConnectionConfigurationSetConfDataType_Encoding_DefaultJson 5031
#define OpcUaId_FX_CM_ConnectionConfigurationConfDataType_Encoding_DefaultBinary 5032
#define OpcUaId_FX_CM_ConnectionConfigurationConfDataType_Encoding_DefaultXml 5033
#define OpcUaId_FX_CM_ConnectionConfigurationConfDataType_Encoding_DefaultJson 5034
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationConfDataType_Encoding_DefaultBinary 5035
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationConfDataType_Encoding_DefaultXml 5036
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationConfDataType_Encoding_DefaultJson 5037
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationConfDataType_Encoding_DefaultBinary 5038
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationConfDataType_Encoding_DefaultXml 5039
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationConfDataType_Encoding_DefaultJson 5040
#define OpcUaId_FX_CM_SubscriberConfigurationConfDataType_Encoding_DefaultBinary 5041
#define OpcUaId_FX_CM_SubscriberConfigurationConfDataType_Encoding_DefaultXml 5042
#define OpcUaId_FX_CM_SubscriberConfigurationConfDataType_Encoding_DefaultJson 5043
#define OpcUaId_FX_CM_AutomationComponentConfigurationConfDataType_Encoding_DefaultBinary 5044
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ConnectionConfigurationSetStateMachine 5045
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_CommunicationFlow \
    5046
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Connection 5047
#define OpcUaId_FX_CM_AutomationComponentConfigurationConfDataType_Encoding_DefaultXml 5048
#define OpcUaId_FX_CM_AutomationComponentConfigurationConfDataType_Encoding_DefaultJson 5049
#define OpcUaId_FX_CM_SecurityKeyServerAddressConfDataType_Encoding_DefaultBinary 5050
#define OpcUaId_FX_CM_SecurityKeyServerAddressConfDataType_Encoding_DefaultXml 5051
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Connection_Endpoint1 \
    5052
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Connection_Endpoint1_ConnectionEndpoint \
    5053
#define OpcUaId_FX_CM_SecurityKeyServerAddressConfDataType_Encoding_DefaultJson 5054
#define OpcUaId_FX_CM_ServerAddressConfDataType_Encoding_DefaultBinary 5055
#define OpcUaId_FX_CM_ServerAddressConfDataType_Encoding_DefaultXml 5056
#define OpcUaId_FX_CM_PortableNodeIdentifier_Encoding_DefaultBinary 5057
#define OpcUaId_FX_CM_PortableNodeIdentifier_Encoding_DefaultXml 5058
#define OpcUaId_FX_CM_PortableNodeIdentifier_Encoding_DefaultJson 5059
#define OpcUaId_FX_CM_ServerAddressConfDataType_Encoding_DefaultJson 5060
#define OpcUaId_FX_CM_AssetVerificationConfDataType_Encoding_DefaultBinary 5061
#define OpcUaId_FX_CM_AssetVerificationConfDataType_Encoding_DefaultXml 5062
#define OpcUaId_FX_CM_AssetVerificationConfDataType_Encoding_DefaultJson 5063
#define OpcUaId_FX_CM_PubSubCommunicationModelConfigurationDataType_Encoding_DefaultBinary 5064
#define OpcUaId_FX_CM_PubSubCommunicationModelConfigurationDataType_Encoding_DefaultXml 5065
#define OpcUaId_FX_CM_PubSubCommunicationModelConfigurationDataType_Encoding_DefaultJson 5066
#define OpcUaId_FX_CM_NodeIdentifier_Encoding_DefaultBinary 5067
#define OpcUaId_FX_CM_NodeIdentifier_Encoding_DefaultXml 5068
#define OpcUaId_FX_CM_NodeIdentifier_Encoding_DefaultJson 5069
#define OpcUaId_FX_CM_NodeIdentifierValuePair_Encoding_DefaultBinary 5070
#define OpcUaId_FX_CM_NodeIdentifierValuePair_Encoding_DefaultXml 5071
#define OpcUaId_FX_CM_NodeIdentifierValuePair_Encoding_DefaultJson 5072
#define OpcUaId_FX_CM_NodeIdTranslationConfDataType_Encoding_DefaultBinary 5073
#define OpcUaId_FX_CM_NodeIdTranslationConfDataType_Encoding_DefaultXml 5074
#define OpcUaId_FX_CM_NodeIdTranslationConfDataType_Encoding_DefaultJson 5075
#define OpcUaId_FX_CM_AddressSelectionDataType_Encoding_DefaultBinary 5076
#define OpcUaId_FX_CM_AddressSelectionDataType_Encoding_DefaultXml 5077
#define OpcUaId_FX_CM_AddressSelectionDataType_Encoding_DefaultJson 5078
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_ConnectionConfigurationSetStateMachine \
    5079
#define OpcUaId_FX_CM_ReceiveQosSelectionDataType_Encoding_DefaultBinary 5080
#define OpcUaId_FX_CM_ReceiveQosSelectionDataType_Encoding_DefaultXml 5081
#define OpcUaId_FX_CM_ReceiveQosSelectionDataType_Encoding_DefaultJson 5082
#define OpcUaId_FX_CM_ConnectionManagerType_Diagnostics 5083
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration 5084
#define OpcUaId_FX_CM_ConnectionManagerType_Capabilities 5085
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Lock 5086
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerLog 5087
#define OpcUaId_FX_CM_ConnectionDiagnosticsDataType_Encoding_DefaultBinary 5088
#define OpcUaId_FX_CM_ConnectionDiagnosticsDataType_Encoding_DefaultXml 5089
#define OpcUaId_FX_CM_ConnectionDiagnosticsDataType_Encoding_DefaultJson 5090
#define OpcUaId_FX_CM_SecurityKeyServerAddressDataType_Encoding_DefaultBinary 5091
#define OpcUaId_FX_CM_SecurityKeyServerAddressDataType_Encoding_DefaultXml 5092
#define OpcUaId_FX_CM_SecurityKeyServerAddressDataType_Encoding_DefaultJson 5093
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Lock 5095
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_AutomationComponentConfiguration_CommunicationModelConfig 5101
#define OpcUaId_FX_CM_Server_Namespaces_http___opcfoundation_org_UA_FX_CM__IsNamespaceSubset 6001
#define OpcUaId_FX_CM_Server_Namespaces_http___opcfoundation_org_UA_FX_CM__NamespacePublicationDate 6002
#define OpcUaId_FX_CM_Server_Namespaces_http___opcfoundation_org_UA_FX_CM__NamespaceUri 6003
#define OpcUaId_FX_CM_Server_Namespaces_http___opcfoundation_org_UA_FX_CM__NamespaceVersion 6004
#define OpcUaId_FX_CM_Server_Namespaces_http___opcfoundation_org_UA_FX_CM__StaticNodeIdTypes 6005
#define OpcUaId_FX_CM_Server_Namespaces_http___opcfoundation_org_UA_FX_CM__StaticNumericNodeIdRange 6006
#define OpcUaId_FX_CM_Server_Namespaces_http___opcfoundation_org_UA_FX_CM__StaticStringNodeIdPattern 6007
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_AutomationComponentConfiguration_AutomationComponentNode \
    6008
#define OpcUaId_FX_CM_AutomationComponentConfigurationType_CommandBundleRequired 6009
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_AutomationComponentConfiguration_CommandBundleRequired 6010
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_AutomationComponentConfiguration_AutomationComponentNode_Selections \
    6011
#define OpcUaId_FX_CM_FxRoot_ConnectionManager_EditConnectionConfigurationSets_InputArguments 6012
#define OpcUaId_FX_CM_FxRoot_ConnectionManager_EditConnectionConfigurationSets_OutputArguments 6013
#define OpcUaId_FX_CM_FxRoot_ConnectionManager_ProcessConnectionConfigurationSets_InputArguments 6014
#define OpcUaId_FX_CM_FxRoot_ConnectionManager_ProcessConnectionConfigurationSets_OutputArguments 6015
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_AutomationComponentConfiguration_CommandBundleRequired \
    6016
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ConnectionConfigurationSetStateMachine_LastTransition 6017
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ConnectionConfigurationSetStateMachine_LastTransition_Id 6018
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ConnectionConfigurationSetStateMachine_CurrentState 6019
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_ServerAddressDataType 6020
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_ServerAddressDataType 6021
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_SecurityKeyServerAddressDataType 6022
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_SecurityKeyServerAddressDataType 6023
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType_LastTransition_Id 6024
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_PortableNodeIdentifierValuePair 6025
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_PortableNodeIdentifierValuePair 6026
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Connection_Endpoint1_ConnectionEndpoint_CleanupTimeout \
    6027
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Connection_Endpoint1_ConnectionEndpoint_CleanupTimeout_Selections \
    6028
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_CloseAndUpdate_InputArguments 6029
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_CloseAndUpdate_OutputArguments 6030
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_PortableKeyValuePair 6031
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_PortableKeyValuePair 6032
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_PortableNodeIdentifier 6033
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_PortableNodeIdentifier 6034
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_PortableRelativePath 6035
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_PortableRelativePath 6036
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_PortableRelativePathElement 6037
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ServerAddress 6038
#define OpcUaId_FX_CM_SecurityKeyServerAddressType_Address 6039
#define OpcUaId_FX_CM_SecurityKeyServerAddressType_Address_Selections 6040
#define OpcUaId_FX_CM_SecurityKeyServerAddressType_SecurityPolicyUri 6041
#define OpcUaId_FX_CM_SecurityKeyServerAddressType_SecurityPolicyUri_Selections 6042
#define OpcUaId_FX_CM_SecurityKeyServerAddressType_ServerUri 6043
#define OpcUaId_FX_CM_SecurityKeyServerAddressType_ServerUri_Selections 6044
#define OpcUaId_FX_CM_AutomationComponentConfigurationType_AutomationComponentNode 6045
#define OpcUaId_FX_CM_AutomationComponentConfigurationType_AutomationComponentNode_Selections 6046
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_PortableRelativePathElement 6047
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_Close_InputArguments 6048
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_GetPosition_InputArguments 6049
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_GetPosition_OutputArguments 6050
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_Open_InputArguments 6051
#define OpcUaId_FX_CM_AutomationComponentConfigurationType_AssetVerification_AssetToVerify 6052
#define OpcUaId_FX_CM_AutomationComponentConfigurationType_AssetVerification_AssetToVerify_Selections 6053
#define OpcUaId_FX_CM_AutomationComponentConfigurationType_AssetVerification_ExpectedVerificationResult 6054
#define OpcUaId_FX_CM_AutomationComponentConfigurationType_AssetVerification_ExpectedVerificationVariables 6055
#define OpcUaId_FX_CM_AutomationComponentConfigurationType_AssetVerification_VerificationMode 6056
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_AutomationComponentConfiguration_AutomationComponentNode 6057
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_AutomationComponentConfiguration_AutomationComponentNode_Selections \
    6058
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Connection_Endpoint1_ConnectionEndpoint_ConnectionEndpointTypeId \
    6059
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Connection_Endpoint1_ConnectionEndpoint_IsPersistent \
    6060
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Connection_Endpoint1_ConnectionEndpoint_IsPersistent_Selections \
    6061
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Connection_Endpoint1_ConnectionEndpoint_IsPreconfigured \
    6062
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_Open_OutputArguments 6063
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_OpenCount 6064
#define OpcUaId_FX_CM_SecurityKeyServerAddressType_UsePushModel 6065
#define OpcUaId_FX_CM_ServerAddressType_Address 6066
#define OpcUaId_FX_CM_ServerAddressType_Address_Selections 6067
#define OpcUaId_FX_CM_ConnectionEndpointParameterType_InputVariableIds 6068
#define OpcUaId_FX_CM_ServerAddressType_SecurityMode 6069
#define OpcUaId_FX_CM_ConnectionEndpointParameterType_Name 6070
#define OpcUaId_FX_CM_ConnectionEndpointParameterType_Name_Selections 6071
#define OpcUaId_FX_CM_ConnectionEndpointParameterType_IsPersistent 6072
#define OpcUaId_FX_CM_ConnectionEndpointParameterType_CleanupTimeout 6073
#define OpcUaId_FX_CM_ConnectionEndpointParameterType_CleanupTimeout_Selections 6074
#define OpcUaId_FX_CM_ServerAddressType_SecurityMode_Selections 6075
#define OpcUaId_FX_CM_ServerAddressType_SecurityPolicyUri 6076
#define OpcUaId_FX_CM_ConnectionEndpointParameterType_IsPersistent_Selections 6077
#define OpcUaId_FX_CM_ServerAddressType_SecurityPolicyUri_Selections 6078
#define OpcUaId_FX_CM_ServerAddressType_ServerUri 6079
#define OpcUaId_FX_CM_ServerAddressType_ServerUri_Selections 6080
#define OpcUaId_FX_CM_ConnectionConfigurationSetStateMachineType_LastTransition 6081
#define OpcUaId_FX_CM_ConnectionEndpointParameterType_OutputVariableIds 6082
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ConnectionConfigurationSetStateMachine_CurrentState_Id 6083
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Connection_Endpoint1_ConnectionEndpoint_Name \
    6084
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ServerAddress_Address 6085
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ServerAddress_Address_Selections 6086
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ServerAddress_SecurityMode 6087
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ServerAddress_SecurityMode_Selections 6088
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ServerAddress_SecurityPolicyUri 6089
#define OpcUaId_FX_CM_FxEditEnum_EnumValues 6090
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema 6091
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_NamespaceUri 6092
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema 6093
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_NamespaceUri 6094
#define OpcUaId_FX_CM_AssetVerificationType_AssetToVerify 6095
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_CommunicationFlowQosDataType 6096
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationType_FunctionalEntityNode 6097
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationType_FunctionalEntityNode_Selections 6098
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ServerAddress_SecurityPolicyUri_Selections 6099
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ServerAddress_ServerUri 6100
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ServerAddress_ServerUri_Selections 6101
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_SecurityKeyServer 6102
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_SecurityKeyServer_Address 6103
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_SecurityKeyServer_Address_Selections 6104
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_SecurityKeyServer_SecurityPolicyUri 6105
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_SecurityKeyServer_SecurityPolicyUri_Selections 6106
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationType_ExpectedVerificationVariables 6107
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationType_ControlGroups 6108
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationType_ConfigurationData 6109
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_SubscriberConfiguration_Address 6110
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_SubscriberConfiguration_Address_Selections 6111
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_SecurityKeyServer_ServerUri 6112
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_Qos 6113
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_Qos_Selections 6114
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_SecurityKeyServer_ServerUri_Selections 6115
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_SecurityKeyServer_UsePushModel 6116
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationType_ConnectionEndpoint_CleanupTimeout 6117
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationType_ConnectionEndpoint_CleanupTimeout_Selections 6118
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationType_ConnectionEndpoint_IsPersistent 6119
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationType_ConnectionEndpoint_IsPersistent_Selections 6120
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationType_ConnectionEndpoint_IsPreconfigured 6121
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationType_ConnectionEndpoint_Name 6122
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint1_FunctionalEntityNode 6123
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint1_FunctionalEntityNode_Selections 6124
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationType_ConnectionEndpoint_Name_Selections 6125
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint1_ConnectionEndpoint_CleanupTimeout 6126
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint1_ConnectionEndpoint_CleanupTimeout_Selections 6127
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint1_ConnectionEndpoint_IsPersistent 6128
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint1_ConnectionEndpoint_IsPersistent_Selections 6129
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint1_ConnectionEndpoint_IsPreconfigured 6130
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint1_ConnectionEndpoint_Name 6131
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint1_ConnectionEndpoint_Name_Selections 6132
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint2_FunctionalEntityNode 6133
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint2_FunctionalEntityNode_Selections 6134
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint1_FunctionalEntityNode 6135
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint1_FunctionalEntityNode_Selections 6136
#define OpcUaId_FX_CM_ConnectionManagerType_Diagnostics_EstablishCallCount 6137
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint2_ConnectionEndpoint_CleanupTimeout 6138
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint2_ConnectionEndpoint_CleanupTimeout_Selections 6139
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint2_ConnectionEndpoint_IsPersistent 6140
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint2_ConnectionEndpoint_IsPersistent_Selections 6141
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint2_ConnectionEndpoint_IsPreconfigured 6142
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint2_ConnectionEndpoint_Name 6143
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint2_ConnectionEndpoint_Name_Selections 6144
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint1_ConnectionEndpoint_CleanupTimeout 6145
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint1_ConnectionEndpoint_CleanupTimeout_Selections \
    6146
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint1_ConnectionEndpoint_IsPersistent 6147
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint1_ConnectionEndpoint_IsPersistent_Selections \
    6148
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint1_ConnectionEndpoint_IsPreconfigured 6149
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint1_ConnectionEndpoint_Name 6150
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint1_ConnectionEndpoint_Name_Selections 6151
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint2_ConnectionEndpoint_CleanupTimeout 6152
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint2_ConnectionEndpoint_CleanupTimeout_Selections \
    6153
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint2_ConnectionEndpoint_IsPersistent 6154
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_CommunicationFlowQosDataType 6155
#define OpcUaId_FX_CM_FxProcessEnum_EnumValues 6156
#define OpcUaId_FX_CM_AssetVerificationType_AssetToVerify_Selections 6157
#define OpcUaId_FX_CM_AssetVerificationType_ExpectedVerificationResult 6158
#define OpcUaId_FX_CM_AssetVerificationType_ExpectedVerificationVariables 6159
#define OpcUaId_FX_CM_AssetVerificationType_VerificationMode 6160
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint2_ConnectionEndpoint_IsPersistent_Selections \
    6161
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint2_ConnectionEndpoint_IsPreconfigured 6162
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint2_ConnectionEndpoint_Name 6163
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint2_ConnectionEndpoint_Name_Selections 6164
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Connection_Endpoint1_ConnectionEndpoint_Name_Selections \
    6165
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Connection_Endpoint1_FunctionalEntityNode \
    6166
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Connection_Endpoint1_FunctionalEntityNode_Selections \
    6167
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Connection_ProcessingResult \
    6168
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_ServerAddress 6169
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_ServerAddress_Address \
    6170
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_ServerAddress_Address_Selections \
    6171
#define OpcUaId_FX_CM_ConnectionEndpointParameterType_ConnectionEndpointTypeId 6172
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationType_ConnectionEndpoint_ConnectionEndpointTypeId 6173
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint1_ConnectionEndpoint_ConnectionEndpointTypeId 6174
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint2_ConnectionEndpoint_ConnectionEndpointTypeId 6175
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint2_FunctionalEntityNode 6176
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint1_ConnectionEndpoint_ConnectionEndpointTypeId \
    6177
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint2_ConnectionEndpoint_ConnectionEndpointTypeId \
    6178
#define OpcUaId_FX_CM_ConnectionEndpointParameterType_CommunicationLinks 6179
#define OpcUaId_FX_CM_ConnectionEndpointParameterType_PreconfiguredPublishedDataSet 6180
#define OpcUaId_FX_CM_ConnectionEndpointParameterType_PreconfiguredSubscribedDataSet 6181
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_SubscriberConfiguration_MessageReceiveTimeout 6182
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_SubscriberConfiguration_MessageReceiveTimeout_Selections \
    6183
#define OpcUaId_FX_CM_PubSubCommunicationModelConfigurationType_Namespaces 6184
#define OpcUaId_FX_CM_PubSubCommunicationModelConfigurationType_TranslationTable 6185
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_NodeIdTranslationDataType 6186
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_NodeIdTranslationDataType 6187
#define OpcUaId_FX_CM_SubscriberConfigurationType_Address 6188
#define OpcUaId_FX_CM_SubscriberConfigurationType_Address_Selections 6189
#define OpcUaId_FX_CM_SubscriberConfigurationType_MessageReceiveTimeout 6190
#define OpcUaId_FX_CM_SubscriberConfigurationType_MessageReceiveTimeout_Selections 6191
#define OpcUaId_FX_CM_SubscriberConfigurationType_ReceiveQos 6192
#define OpcUaId_FX_CM_SubscriberConfigurationType_ReceiveQos_Selections 6193
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_TransportProfileUri 6194
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_TransportProfileUri_Selections 6195
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_HeaderLayoutUri 6196
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_HeaderLayoutUri_Selections 6197
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_Read_InputArguments 6198
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_Read_OutputArguments 6199
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_SetPosition_InputArguments 6200
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_Size 6201
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_UserWritable 6202
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_Writable 6203
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_Write_InputArguments 6204
#define OpcUaId_FX_CM_ConnectionManagerType_AggregatedCurrentState 6205
#define OpcUaId_FX_CM_ConnectionManagerCapabilitiesType_Capability 6206
#define OpcUaId_FX_CM_ConnectionManagerCapabilitiesType_MaxConnectionConfigurationSets 6207
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_SecurityGroups 6208
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_PubSubKeyPushTargets 6209
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_ServerAddress_SecurityMode \
    6210
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_ServerAddress_SecurityMode_Selections \
    6211
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_ServerAddress_SecurityPolicyUri \
    6212
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_ServerAddress_SecurityPolicyUri_Selections \
    6213
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_ServerAddress_ServerUri \
    6214
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_ServerAddress_ServerUri_Selections \
    6215
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_ConnectionConfigurationSetStateMachine_CurrentState \
    6216
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_ConnectionConfigurationSetStateMachine_CurrentState_Id \
    6217
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_ConnectionConfigurationSetStateMachine_LastTransition \
    6218
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Version 6219
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_ConnectionConfigurationSetStateMachine_LastTransition_Id \
    6220
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Lock_BreakLock_OutputArguments \
    6221
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Lock_ExitLock_OutputArguments \
    6222
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Lock_InitLock_InputArguments \
    6223
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Lock_InitLock_OutputArguments \
    6224
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Lock_Locked 6225
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Lock_LockingClient \
    6226
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Lock_LockingUser 6227
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Lock_RemainingLockTime \
    6228
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint2_FunctionalEntityNode_Selections 6229
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Lock_RenewLock_OutputArguments \
    6230
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_RollbackOnError 6231
#define OpcUaId_FX_CM_ConnectionStateEnum_EnumValues 6232
#define OpcUaId_FX_CM_LastActivityMask_OptionSetValues 6233
#define OpcUaId_FX_CM_FxErrorEnum_EnumValues 6234
#define OpcUaId_FX_CM_ConnectionManagerCapabilitiesType_MonitorsLocalConnectionEndpoints 6235
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ConnectionConfigurationSetStateMachine_AvailableStates 6236
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ConnectionConfigurationSetStateMachine_AvailableTransitions 6237
#define OpcUaId_FX_CM_ConnectionManagerCapabilitiesType_MonitorsAllConnectionEndpoints 6238
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_ConnectionsDiagnostics 6239
#define OpcUaId_FX_CM_ConnectionManagerType_Diagnostics_CloseCallCount 6240
#define OpcUaId_FX_CM_ConnectionManagerType_Diagnostics_EstablishCallFailedCount 6241
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_Deprecated 6242
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_Deprecated 6243
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerLog_GetRecords_InputArguments 6244
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerLog_GetRecords_OutputArguments 6245
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_ConnectionDiagnosticsDataType 6246
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_ConnectionDiagnosticsDataType 6247
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerLog_MaxRecords 6248
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerLog_MaxStorageDuration 6249
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerLog_MinimumSeverity 6250
#define OpcUaId_FX_CM_ConnectionManagerType_Diagnostics_CloseCallFailedCount 6251
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint2_ConfigurationData 6269
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint2_ControlGroups 6270
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint1_ConfigurationData 6280
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint1_ControlGroups 6281
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint1_ExpectedVerificationVariables 6282
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint1_ConfigurationData 6283
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint1_ControlGroups 6284
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint1_ExpectedVerificationVariables 6285
#define OpcUaId_FX_CM_ConnectionConfigurationType_Endpoint2_ExpectedVerificationVariables 6298
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint2_ConfigurationData 6299
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint2_ControlGroups 6300
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Connection_Endpoint2_ExpectedVerificationVariables 6301
#define OpcUaId_FX_CM_ConnectionConfigurationSetEventType_ConnectionConfigurationSetNode 6352
#define OpcUaId_FX_CM_ConnectionConfigurationSetEventType_Name 6353
#define OpcUaId_FX_CM_ConnectionConfigurationSetEventType_Action 6354
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Lock_BreakLock_OutputArguments 6382
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Lock_ExitLock_OutputArguments 6383
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Lock_InitLock_InputArguments 6384
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Lock_InitLock_OutputArguments 6385
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Lock_Locked 6386
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Lock_LockingClient 6387
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Lock_LockingUser 6388
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Lock_RemainingLockTime 6389
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Lock_RenewLock_OutputArguments 6390
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Edit 6487
#define OpcUaId_FX_CM_ConnectionEndpointParameterType_IsPreconfigured 6498
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_SecurityMode 6520
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_SecurityMode_Selections 6521
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_SecurityGroupId 6524
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationType_SecurityGroupId_Selections 6525
#define OpcUaId_FX_CM_AssetVerificationType_ExpectedAdditionalVerificationVariables 6526
#define OpcUaId_FX_CM_AutomationComponentConfigurationType_AssetVerification_ExpectedAdditionalVerificationVariables \
    6527
#define OpcUaId_FX_CM_PubSubCommunicationModelConfigurationType_PubSubConfiguration 6528
#define OpcUaId_FX_CM_PubSubCommunicationModelConfigurationType_ConfigurationReferences 6529
#define OpcUaId_FX_CM_PubSubCommunicationModelConfigurationType_ConfigurationValues 6530
#define OpcUaId_FX_CM_FxRoot_ConnectionManager_EditConnectionConfigurationSets 7001
#define OpcUaId_FX_CM_FxRoot_ConnectionManager_ProcessConnectionConfigurationSets 7002
#define OpcUaId_FX_CM_ConnectionManagerConfigurationType_CloseAndUpdate 7003
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerLog_GetRecords 7004
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_CloseAndUpdate 7011
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_Close 7012
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_GetPosition 7013
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_Open 7014
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_Read 7015
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_SetPosition 7016
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionManagerConfiguration_Write 7017
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Lock_BreakLock 7018
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Lock_ExitLock 7019
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Lock_InitLock 7020
#define OpcUaId_FX_CM_ConnectionManagerType_ConnectionConfigurationSets_ConnectionConfigurationSet_Lock_RenewLock 7021
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Lock_BreakLock 7037
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Lock_ExitLock 7038
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Lock_InitLock 7039
#define OpcUaId_FX_CM_ConnectionConfigurationSetType_Lock_RenewLock 7040
#define OpcUaId_FX_CM_ConnectionConfigurationSetConfDataType 13003
#define OpcUaId_FX_CM_ConnectionConfigurationConfDataType 13006
#define OpcUaId_FX_CM_ConnectionEndpointConfigurationConfDataType 13009
#define OpcUaId_FX_CM_CommunicationFlowConfigurationConfDataType 13012
#define OpcUaId_FX_CM_PubSubCommunicationFlowConfigurationConfDataType 13015
#define OpcUaId_FX_CM_SubscriberConfigurationConfDataType 13018
#define OpcUaId_FX_CM_AutomationComponentConfigurationConfDataType 13021
#define OpcUaId_FX_CM_SecurityKeyServerAddressConfDataType 13024
#define OpcUaId_FX_CM_ServerAddressConfDataType 13027
#define OpcUaId_FX_CM_AssetVerificationConfDataType 13030
#define OpcUaId_FX_CM_CommunicationModelConfigurationDataType 13033
#define OpcUaId_FX_CM_PubSubCommunicationModelConfigurationDataType 13036
#define OpcUaId_FX_CM_NodeIdentifier 13039
#define OpcUaId_FX_CM_NodeIdentifierValuePair 13042
#define OpcUaId_FX_CM_NodeIdTranslationConfDataType 13045
#define OpcUaId_FX_CM_AddressSelectionDataType 13048
#define OpcUaId_FX_CM_ReceiveQosSelectionDataType 13051
#define OpcUaId_FX_CM_ConnectionConfigurationSetOperation 13054
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_ConnectionConfigurationSetConfDataType 16001
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_ConnectionConfigurationSetConfDataType 16002
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_ConnectionConfigurationConfDataType 16003
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_ConnectionConfigurationConfDataType 16004
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_ConnectionEndpointConfigurationConfDataType 16005
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_ConnectionEndpointConfigurationConfDataType 16006
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_PubSubCommunicationFlowConfigurationConfDataType 16007
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_PubSubCommunicationFlowConfigurationConfDataType 16008
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_SubscriberConfigurationConfDataType 16009
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_SubscriberConfigurationConfDataType 16010
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_AutomationComponentConfigurationConfDataType 16011
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_AutomationComponentConfigurationConfDataType 16012
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_SecurityKeyServerAddressConfDataType 16013
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_SecurityKeyServerAddressConfDataType 16014
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_ServerAddressConfDataType 16015
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_ServerAddressConfDataType 16016
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_AssetVerificationConfDataType 16017
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_AssetVerificationConfDataType 16018
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_PubSubCommunicationModelConfigurationDataType 16019
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_PubSubCommunicationModelConfigurationDataType 16020
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_NodeIdentifier 16021
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_NodeIdentifier 16022
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_NodeIdentifierValuePair 16023
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_NodeIdentifierValuePair 16024
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_NodeIdTranslationConfDataType 16025
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_NodeIdTranslationConfDataType 16026
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_AddressSelectionDataType 16027
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_AddressSelectionDataType 16028
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_BinarySchema_ReceiveQosSelectionDataType 16029
#define OpcUaId_FX_CM_Opc_Ua_FX_CM_XmlSchema_ReceiveQosSelectionDataType 16030
#define OpcUaId_FX_CM_ConnectionConfigurationSetOperation_OptionSetValues 16031
#define OpcUaId_FX_CM_ConnectionManagerConfigurationType_CloseAndUpdate_InputArguments 16032
#define OpcUaId_FX_CM_ConnectionManagerConfigurationType_CloseAndUpdate_OutputArguments 16033
#endif
