/*
 * Licensed to Systerel under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Systerel licenses this file to you under the Apache
 * License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#ifndef OPCUA_FX_DATA_IDENTIFIERS_H
#define OpcUaId_FX_Data_PubSubConnectionEndpointModeEnum 31
#define OpcUaId_FX_Data_FxRoot 71
#define OpcUaId_FX_Data_Server_Namespaces_http___opcfoundation_org_UA_FX_Data_ 81
#define OpcUaId_FX_Data_Server_Namespaces_http___opcfoundation_org_UA_FX_Data__IsNamespaceSubset 177
#define OpcUaId_FX_Data_Server_Namespaces_http___opcfoundation_org_UA_FX_Data__NamespacePublicationDate 178
#define OpcUaId_FX_Data_Server_Namespaces_http___opcfoundation_org_UA_FX_Data__NamespaceUri 179
#define OpcUaId_FX_Data_Server_Namespaces_http___opcfoundation_org_UA_FX_Data__NamespaceVersion 180
#define OpcUaId_FX_Data_Server_Namespaces_http___opcfoundation_org_UA_FX_Data__StaticNodeIdTypes 181
#define OpcUaId_FX_Data_Server_Namespaces_http___opcfoundation_org_UA_FX_Data__StaticNumericNodeIdRange 182
#define OpcUaId_FX_Data_Server_Namespaces_http___opcfoundation_org_UA_FX_Data__StaticStringNodeIdPattern 183
#define OpcUaId_FX_Data_FxCommandMask 1024
#define OpcUaId_FX_Data_AuditUpdateMethodResultEventType 1025
#define OpcUaId_FX_Data_NodeIdValuePair 1028
#define OpcUaId_FX_Data_AssetVerificationModeEnum 1029
#define OpcUaId_FX_Data_PubSubCommunicationLinkConfigurationDataType 1031
#define OpcUaId_FX_Data_CommunicationConfigurationResultDataType 1033
#define OpcUaId_FX_Data_NodeIdArray 1034
#define OpcUaId_FX_Data_AssetVerificationResultEnum 1037
#define OpcUaId_FX_Data_AssetVerificationResultDataType 1038
#define OpcUaId_FX_Data_PubSubCommunicationConfigurationResultDataType 1039
#define OpcUaId_FX_Data_ConnectionEndpointConfigurationDataType 1044
#define OpcUaId_FX_Data_PubSubCommunicationConfigurationDataType 1045
#define OpcUaId_FX_Data_CommunicationConfigurationDataType 1046
#define OpcUaId_FX_Data_AssetVerificationDataType 1048
#define OpcUaId_FX_Data_NodeIdValuePair_Encoding_DefaultBinary 1093
#define OpcUaId_FX_Data_NodeIdValuePair_Encoding_DefaultXml 1094
#define OpcUaId_FX_Data_NodeIdValuePair_Encoding_DefaultJson 1095
#define OpcUaId_FX_Data_PubSubCommunicationLinkConfigurationDataType_Encoding_DefaultBinary 1102
#define OpcUaId_FX_Data_PubSubCommunicationLinkConfigurationDataType_Encoding_DefaultXml 1103
#define OpcUaId_FX_Data_PubSubCommunicationLinkConfigurationDataType_Encoding_DefaultJson 1104
#define OpcUaId_FX_Data_CommunicationConfigurationResultDataType_Encoding_DefaultBinary 1108
#define OpcUaId_FX_Data_CommunicationConfigurationResultDataType_Encoding_DefaultXml 1109
#define OpcUaId_FX_Data_CommunicationConfigurationResultDataType_Encoding_DefaultJson 1110
#define OpcUaId_FX_Data_NodeIdArray_Encoding_DefaultBinary 1111
#define OpcUaId_FX_Data_NodeIdArray_Encoding_DefaultXml 1112
#define OpcUaId_FX_Data_NodeIdArray_Encoding_DefaultJson 1113
#define OpcUaId_FX_Data_ConnectionEndpointConfigurationDataType_Encoding_DefaultBinary 1141
#define OpcUaId_FX_Data_ConnectionEndpointConfigurationDataType_Encoding_DefaultXml 1142
#define OpcUaId_FX_Data_ConnectionEndpointConfigurationDataType_Encoding_DefaultJson 1143
#define OpcUaId_FX_Data_PubSubCommunicationConfigurationDataType_Encoding_DefaultBinary 1144
#define OpcUaId_FX_Data_PubSubCommunicationConfigurationDataType_Encoding_DefaultXml 1145
#define OpcUaId_FX_Data_PubSubCommunicationConfigurationDataType_Encoding_DefaultJson 1146
#define OpcUaId_FX_Data_CommunicationConfigurationDataType_Encoding_DefaultBinary 1147
#define OpcUaId_FX_Data_CommunicationConfigurationDataType_Encoding_DefaultXml 1148
#define OpcUaId_FX_Data_CommunicationConfigurationDataType_Encoding_DefaultJson 1149
#define OpcUaId_FX_Data_AssetVerificationDataType_Encoding_DefaultBinary 1153
#define OpcUaId_FX_Data_AssetVerificationDataType_Encoding_DefaultXml 1154
#define OpcUaId_FX_Data_AssetVerificationDataType_Encoding_DefaultJson 1155
#define OpcUaId_FX_Data_AssetVerificationResultDataType_Encoding_DefaultBinary 1205
#define OpcUaId_FX_Data_AssetVerificationResultDataType_Encoding_DefaultXml 1206
#define OpcUaId_FX_Data_AssetVerificationResultDataType_Encoding_DefaultJson 1207
#define OpcUaId_FX_Data_PubSubCommunicationConfigurationResultDataType_Encoding_DefaultBinary 1208
#define OpcUaId_FX_Data_PubSubCommunicationConfigurationResultDataType_Encoding_DefaultXml 1209
#define OpcUaId_FX_Data_PubSubCommunicationConfigurationResultDataType_Encoding_DefaultJson 1210
#define OpcUaId_FX_Data_FxCommandMask_OptionSetValues 1225
#define OpcUaId_FX_Data_FunctionalEntityVerificationResultEnum 3002
#define OpcUaId_FX_Data_RelatedEndpointDataType 3003
#define OpcUaId_FX_Data_PubSubReserveCommunicationIds2DataType 3005
#define OpcUaId_FX_Data_PubSubConnectionEndpointParameterDataType 3006
#define OpcUaId_FX_Data_CommunicationLinkConfigurationDataType 3007
#define OpcUaId_FX_Data_ConnectionEndpointConfigurationResultDataType 3008
#define OpcUaId_FX_Data_ConnectionEndpointParameterDataType 3009
#define OpcUaId_FX_Data_ConnectionEndpointDefinitionDataType 3011
#define OpcUaId_FX_Data_PubSubReserveCommunicationIdsResult2DataType 3013
#define OpcUaId_FX_Data_ReserveCommunicationIdsDataType 3017
#define OpcUaId_FX_Data_PubSubReserveCommunicationIdsDataType 3018
#define OpcUaId_FX_Data_ReserveCommunicationIdsResultDataType 3019
#define OpcUaId_FX_Data_PubSubReserveCommunicationIdsResultDataType 3020
#define OpcUaId_FX_Data_RelatedEndpointDataType_Encoding_DefaultBinary 5001
#define OpcUaId_FX_Data_RelatedEndpointDataType_Encoding_DefaultXml 5002
#define OpcUaId_FX_Data_RelatedEndpointDataType_Encoding_DefaultJson 5003
#define OpcUaId_FX_Data_PubSubReserveCommunicationIds2DataType_Encoding_DefaultBinary 5004
#define OpcUaId_FX_Data_PubSubReserveCommunicationIds2DataType_Encoding_DefaultXml 5005
#define OpcUaId_FX_Data_PubSubReserveCommunicationIds2DataType_Encoding_DefaultJson 5006
#define OpcUaId_FX_Data_PubSubReserveCommunicationIdsResult2DataType_Encoding_DefaultBinary 5007
#define OpcUaId_FX_Data_PubSubReserveCommunicationIdsResult2DataType_Encoding_DefaultXml 5008
#define OpcUaId_FX_Data_PubSubReserveCommunicationIdsResult2DataType_Encoding_DefaultJson 5009
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin 5019
#define OpcUaId_FX_Data_CommunicationLinkConfigurationDataType_Encoding_DefaultBinary 5033
#define OpcUaId_FX_Data_CommunicationLinkConfigurationDataType_Encoding_DefaultXml 5034
#define OpcUaId_FX_Data_CommunicationLinkConfigurationDataType_Encoding_DefaultJson 5035
#define OpcUaId_FX_Data_ConnectionEndpointConfigurationResultDataType_Encoding_DefaultBinary 5036
#define OpcUaId_FX_Data_ConnectionEndpointConfigurationResultDataType_Encoding_DefaultXml 5037
#define OpcUaId_FX_Data_ConnectionEndpointConfigurationResultDataType_Encoding_DefaultJson 5038
#define OpcUaId_FX_Data_ConnectionEndpointParameterDataType_Encoding_DefaultBinary 5039
#define OpcUaId_FX_Data_ConnectionEndpointParameterDataType_Encoding_DefaultXml 5040
#define OpcUaId_FX_Data_ConnectionEndpointParameterDataType_Encoding_DefaultJson 5041
#define OpcUaId_FX_Data_ConnectionEndpointDefinitionDataType_Encoding_DefaultBinary 5054
#define OpcUaId_FX_Data_ConnectionEndpointDefinitionDataType_Encoding_DefaultXml 5055
#define OpcUaId_FX_Data_ConnectionEndpointDefinitionDataType_Encoding_DefaultJson 5056
#define OpcUaId_FX_Data_PubSubConnectionEndpointParameterDataType_Encoding_DefaultBinary 5060
#define OpcUaId_FX_Data_PubSubConnectionEndpointParameterDataType_Encoding_DefaultXml 5061
#define OpcUaId_FX_Data_PubSubConnectionEndpointParameterDataType_Encoding_DefaultJson 5062
#define OpcUaId_FX_Data_ReserveCommunicationIdsDataType_Encoding_DefaultBinary 5064
#define OpcUaId_FX_Data_ReserveCommunicationIdsDataType_Encoding_DefaultXml 5065
#define OpcUaId_FX_Data_ReserveCommunicationIdsDataType_Encoding_DefaultJson 5081
#define OpcUaId_FX_Data_PubSubReserveCommunicationIdsDataType_Encoding_DefaultBinary 5082
#define OpcUaId_FX_Data_PubSubReserveCommunicationIdsDataType_Encoding_DefaultXml 5083
#define OpcUaId_FX_Data_PubSubReserveCommunicationIdsDataType_Encoding_DefaultJson 5084
#define OpcUaId_FX_Data_ReserveCommunicationIdsResultDataType_Encoding_DefaultBinary 5085
#define OpcUaId_FX_Data_ReserveCommunicationIdsResultDataType_Encoding_DefaultXml 5086
#define OpcUaId_FX_Data_ReserveCommunicationIdsResultDataType_Encoding_DefaultJson 5087
#define OpcUaId_FX_Data_PubSubReserveCommunicationIdsResultDataType_Encoding_DefaultBinary 5088
#define OpcUaId_FX_Data_PubSubReserveCommunicationIdsResultDataType_Encoding_DefaultXml 5089
#define OpcUaId_FX_Data_PubSubReserveCommunicationIdsResultDataType_Encoding_DefaultJson 5090
#define OpcUaId_FX_Data_AuditUpdateMethodResultEventType_OutputArguments 6001
#define OpcUaId_FX_Data_AuditUpdateMethodResultEventType_StatusCodeId 6002
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_PubSubReserveCommunicationIds2DataType 6003
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_PubSubReserveCommunicationIds2DataType 6004
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_PubSubReserveCommunicationIdsResult2DataType 6005
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_PubSubReserveCommunicationIdsResult2DataType 6006
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_ConnectionEndpointDefinitionDataType 6008
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_ConnectionEndpointDefinitionDataType 6009
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_Deprecated 6011
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_Deprecated 6012
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema 6022
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_NamespaceUri 6023
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema 6024
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_NamespaceUri 6025
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_AssetVerificationDataType 6028
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_AssetVerificationDataType 6029
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_AssetVerificationResultDataType 6161
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_AssetVerificationResultDataType 6162
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_CommunicationConfigurationDataType 6163
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_CommunicationConfigurationDataType 6164
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_PubSubCommunicationConfigurationDataType 6165
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_PubSubCommunicationConfigurationDataType 6166
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_CommunicationConfigurationResultDataType 6167
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_CommunicationConfigurationResultDataType 6168
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_AddApplication_InputArguments 6170
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_PubSubCommunicationConfigurationResultDataType 6171
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_PubSubCommunicationConfigurationResultDataType 6172
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_CommunicationLinkConfigurationDataType 6173
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_CommunicationLinkConfigurationDataType 6174
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_PubSubCommunicationLinkConfigurationDataType 6177
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_PubSubCommunicationLinkConfigurationDataType 6178
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_ConnectionEndpointConfigurationDataType 6179
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_ConnectionEndpointConfigurationDataType 6180
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_ConnectionEndpointConfigurationResultDataType 6181
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_ConnectionEndpointConfigurationResultDataType 6182
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_ConnectionEndpointParameterDataType 6185
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_ConnectionEndpointParameterDataType 6186
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_NodeIdArray 6193
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_NodeIdArray 6194
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_NodeIdValuePair 6195
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_NodeIdValuePair 6196
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_RelatedEndpointDataType 6217
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_RelatedEndpointDataType 6218
#define OpcUaId_FX_Data_PubSubConnectionEndpointModeEnum_EnumValues 6240
#define OpcUaId_FX_Data_AssetVerificationResultEnum_EnumValues 6326
#define OpcUaId_FX_Data_AssetVerificationModeEnum_EnumValues 6327
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_PubSubConnectionEndpointParameterDataType 6329
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_PubSubConnectionEndpointParameterDataType 6330
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_AddEndpoint_InputArguments 6331
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_AddIdentity_InputArguments 6332
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_Applications 6400
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_ApplicationsExclude 6402
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_Endpoints 6403
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_EndpointsExclude 6404
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_Identities 6405
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_RemoveApplication_InputArguments 6406
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_RemoveEndpoint_InputArguments 6407
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_RemoveIdentity_InputArguments 6408
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_ReserveCommunicationIdsDataType 6411
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_ReserveCommunicationIdsDataType 6412
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_PubSubReserveCommunicationIdsDataType 6413
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_PubSubReserveCommunicationIdsDataType 6414
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_ReserveCommunicationIdsResultDataType 6415
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_ReserveCommunicationIdsResultDataType 6416
#define OpcUaId_FX_Data_Opc_Ua_Fx_BinarySchema_PubSubReserveCommunicationIdsResultDataType 6417
#define OpcUaId_FX_Data_Opc_Ua_Fx_XmlSchema_PubSubReserveCommunicationIdsResultDataType 6418
#define OpcUaId_FX_Data_FunctionalEntityVerificationResultEnum_EnumValues 6532
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_AddApplication 7027
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_AddEndpoint 7028
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_AddIdentity 7029
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_RemoveApplication 7030
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_RemoveEndpoint 7031
#define OpcUaId_FX_Data_Server_ServerCapabilities_RoleSet_ConnectionAdmin_RemoveIdentity 7032
#endif
