/* Copyright (C) Systerel SAS 2019, all rights reserved. */

#include "pubsub_config_static.h"

#include <stdbool.h>
#include <string.h>

#include "sopc_assert.h"

// DO NOT EDIT THIS FILE HAS BEEN GENERATED BY generate-s2opc_pubsub-static-config.py


static SOPC_ReaderGroup* SOPC_PubSubConfig_SetSubMessageAt(SOPC_PubSubConnection* connection,
                                                           uint16_t index,
                                                           SOPC_SecurityMode_Type securityMode,
                                                           uint16_t groupId,
                                                           uint32_t groupVersion,
                                                           uint32_t publisherId,
                                                           uint16_t nbDataSets,
                                                           const char * topic)
{
    SOPC_ReaderGroup* readerGroup = SOPC_PubSubConnection_Get_ReaderGroup_At(connection, index);
    SOPC_ASSERT(readerGroup != NULL);
    SOPC_ReaderGroup_Set_SecurityMode(readerGroup, securityMode);
    SOPC_ReaderGroup_Set_GroupVersion(readerGroup, groupVersion);
    SOPC_ReaderGroup_Set_GroupId(readerGroup, groupId);
    SOPC_ReaderGroup_Set_PublisherId_UInteger(readerGroup, publisherId);
    SOPC_ASSERT(nbDataSets < 0x100);
    bool allocSuccess = SOPC_ReaderGroup_Allocate_DataSetReader_Array(readerGroup, (uint8_t) nbDataSets);
    SOPC_ASSERT(allocSuccess);
    if (NULL != topic)
    {
    	SOPC_ReaderGroup_Set_MqttTopic(readerGroup,topic);
    }
    else
    {
    	SOPC_ReaderGroup_Set_MqttTopic(readerGroup,SOPC_Compute_Default_MqttTopic(publisherId, groupId));
    	//SOPC_ReaderGroup_Set_Default_MqttTopic(readerGroup, publisherId, groupId);
    }
    
    return readerGroup;
}


static SOPC_DataSetReader* SOPC_PubSubConfig_SetReaderAt(SOPC_ReaderGroup* readerGroup,
                                                         uint16_t index,
                                                         uint16_t writerId,
                                                         double interval)
{
    SOPC_ASSERT(index < 0x100);
    SOPC_DataSetReader* reader = SOPC_ReaderGroup_Get_DataSetReader_At(readerGroup, (uint8_t) index);
    SOPC_ASSERT(reader != NULL);
    SOPC_DataSetReader_Set_DataSetWriterId(reader, writerId);
    SOPC_DataSetReader_Set_ReceiveTimeout(reader, 2.0 * interval);
    return reader;
}


static bool SOPC_PubSubConfig_SetSubNbVariables(SOPC_DataSetReader* reader, uint16_t nbVar)
{
    return SOPC_DataSetReader_Allocate_FieldMetaData_Array(reader, SOPC_TargetVariablesDataType, nbVar);
}


static void SOPC_PubSubConfig_SetSubVariableAt(SOPC_DataSetReader* reader,
                                               uint16_t index,
                                               char* strNodeId,
                                               SOPC_BuiltinId builtinType)
{
    SOPC_FieldMetaData* fieldmetadata = SOPC_DataSetReader_Get_FieldMetaData_At(reader, index);
    SOPC_ASSERT(fieldmetadata != NULL);

    /* fieldmetadata: type the field */
    SOPC_FieldMetaData_Set_ValueRank(fieldmetadata, -1);
    SOPC_FieldMetaData_Set_BuiltinType(fieldmetadata, builtinType);

    /* FieldTarget: link to the source/target data */
    SOPC_FieldTarget* fieldTarget = SOPC_FieldMetaData_Get_TargetVariable(fieldmetadata);
    SOPC_ASSERT(fieldTarget != NULL);
    SOPC_NodeId* nodeId = SOPC_NodeId_FromCString(strNodeId, (int32_t) strlen(strNodeId));
    SOPC_FieldTarget_Set_NodeId(fieldTarget, nodeId);
    SOPC_FieldTarget_Set_AttributeId(fieldTarget, 13); // Value => AttributeId=13
}

SOPC_PubSubConfiguration* SOPC_PubSubConfig_GetStatic(void)
{
    bool alloc = true;
    SOPC_PubSubConfiguration* config = SOPC_PubSubConfiguration_Create();
    
    SOPC_PubSubConnection* connection = NULL;

    /* 1 connection Sub */
    alloc = SOPC_PubSubConfiguration_Allocate_SubConnection_Array(config, 1);
    
    /** Subscriber connection 0 **/
    
    if (alloc)
    {
        // Set subscriber id and address
        connection = SOPC_PubSubConfiguration_Get_SubConnection_At(config, 0);
        alloc = SOPC_PubSubConnection_Set_Address(connection, "opc.udp://232.1.2.100:4840");
    }

    if (alloc)
    {
        // 2 sub messages
        alloc = SOPC_PubSubConnection_Allocate_ReaderGroup_Array(connection, 2);
    }

        
    SOPC_DataSetReader* dsReader = NULL;
    SOPC_ReaderGroup* readerGroup = NULL;
    /*** Sub Message 14 ***/
    
    if (alloc)
    {
        // Allocate 1 datasets
        // GroupId = 14
        // GroupVersion = 1
        // PubId = 42
        // topic = NULL
        readerGroup = SOPC_PubSubConfig_SetSubMessageAt(connection, 0, SOPC_SecurityMode_None, 14, 1, 42, 1, NULL);
        alloc = NULL != readerGroup;
    }
    
    /*** DataSetMessage No 1 of message 14 ***/
    
    if (alloc)
    {
        // Interval = 100.000000 ms
        dsReader = SOPC_PubSubConfig_SetReaderAt(readerGroup, 0, 0, 100.000000);
        alloc = NULL != dsReader;
    }
    
    if (alloc)
    {
        alloc = SOPC_PubSubConfig_SetSubNbVariables(dsReader, 2);

    }

    if (alloc)
    {
    
        SOPC_PubSubConfig_SetSubVariableAt(dsReader, 0, "ns=1;s=SubBool", SOPC_Boolean_Id); // varBool
        SOPC_PubSubConfig_SetSubVariableAt(dsReader, 1, "ns=1;s=SubString", SOPC_String_Id); // varString
    }
    
    /*** Sub Message 15 ***/
    
    if (alloc)
    {
        // Allocate 1 datasets
        // GroupId = 15
        // GroupVersion = 1
        // PubId = 42
        // topic = NULL
        readerGroup = SOPC_PubSubConfig_SetSubMessageAt(connection, 1, SOPC_SecurityMode_None, 15, 1, 42, 1, NULL);
        alloc = NULL != readerGroup;
    }
    
    /*** DataSetMessage No 1 of message 15 ***/
    
    if (alloc)
    {
        // Interval = 1000.000000 ms
        dsReader = SOPC_PubSubConfig_SetReaderAt(readerGroup, 0, 0, 1000.000000);
        alloc = NULL != dsReader;
    }
    
    if (alloc)
    {
        alloc = SOPC_PubSubConfig_SetSubNbVariables(dsReader, 2);

    }

    if (alloc)
    {
    
        SOPC_PubSubConfig_SetSubVariableAt(dsReader, 0, "ns=1;s=SubInt", SOPC_Int64_Id); // varInt
        SOPC_PubSubConfig_SetSubVariableAt(dsReader, 1, "ns=1;s=SubUInt", SOPC_UInt64_Id); // varUInt
    }
    

    if (!alloc)
    {
        SOPC_PubSubConfiguration_Delete(config);
        return NULL;
    }

    return config;
}
    
