var searchData=
[
  ['request_5fhandle_5fbs_5f_5fclient_5ffresh_5freq_5fhandle',['request_handle_bs__client_fresh_req_handle',['../request__handle__bs_8c.html#a3b1d1ae29f4c84a845361f1164207c90',1,'request_handle_bs__client_fresh_req_handle(const constants__t_msg_type_i request_handle_bs__resp_typ, constants__t_request_handle_i *const request_handle_bs__request_handle):&#160;request_handle_bs.c'],['../request__handle__bs_8h.html#a3b1d1ae29f4c84a845361f1164207c90',1,'request_handle_bs__client_fresh_req_handle(const constants__t_msg_type_i request_handle_bs__resp_typ, constants__t_request_handle_i *const request_handle_bs__request_handle):&#160;request_handle_bs.c']]],
  ['request_5fhandle_5fbs_5f_5fclient_5fremove_5freq_5fhandle',['request_handle_bs__client_remove_req_handle',['../request__handle__bs_8c.html#a568bdba2304255d8e6ce341bc52e0c45',1,'request_handle_bs__client_remove_req_handle(const constants__t_request_handle_i request_handle_bs__req_handle):&#160;request_handle_bs.c'],['../request__handle__bs_8h.html#a568bdba2304255d8e6ce341bc52e0c45',1,'request_handle_bs__client_remove_req_handle(const constants__t_request_handle_i request_handle_bs__req_handle):&#160;request_handle_bs.c']]],
  ['request_5fhandle_5fbs_5f_5fclient_5fvalidate_5fresponse_5frequest_5fhandle',['request_handle_bs__client_validate_response_request_handle',['../request__handle__bs_8c.html#a0765741d1dcdf77632fc2ac0b04fa648',1,'request_handle_bs__client_validate_response_request_handle(const constants__t_request_handle_i request_handle_bs__req_handle, const constants__t_msg_type_i request_handle_bs__resp_typ, t_bool *const request_handle_bs__ret):&#160;request_handle_bs.c'],['../request__handle__bs_8h.html#a0765741d1dcdf77632fc2ac0b04fa648',1,'request_handle_bs__client_validate_response_request_handle(const constants__t_request_handle_i request_handle_bs__req_handle, const constants__t_msg_type_i request_handle_bs__resp_typ, t_bool *const request_handle_bs__ret):&#160;request_handle_bs.c']]],
  ['request_5fhandle_5fbs_5f_5finitialisation',['request_handle_bs__INITIALISATION',['../request__handle__bs_8c.html#a192d38022b510b68993a7327d54d61ee',1,'request_handle_bs__INITIALISATION(void):&#160;request_handle_bs.c'],['../request__handle__bs_8h.html#a192d38022b510b68993a7327d54d61ee',1,'request_handle_bs__INITIALISATION(void):&#160;request_handle_bs.c']]],
  ['request_5fhandle_5fbs_5f_5fis_5fvalid_5freq_5fhandle',['request_handle_bs__is_valid_req_handle',['../request__handle__bs_8c.html#a1f9513ceeb7804f1330f90b20dece70b',1,'request_handle_bs__is_valid_req_handle(const constants__t_request_handle_i request_handle_bs__req_handle, t_bool *const request_handle_bs__ret):&#160;request_handle_bs.c'],['../request__handle__bs_8h.html#a1f9513ceeb7804f1330f90b20dece70b',1,'request_handle_bs__is_valid_req_handle(const constants__t_request_handle_i request_handle_bs__req_handle, t_bool *const request_handle_bs__ret):&#160;request_handle_bs.c']]],
  ['request_5fhandle_5fbs_5f_5freq_5fhandle_5fdo_5fnothing',['request_handle_bs__req_handle_do_nothing',['../request__handle__bs_8c.html#a4389d5a3380a1fb1e8df2ebce205a015',1,'request_handle_bs__req_handle_do_nothing(const constants__t_request_handle_i request_handle_bs__req_handle):&#160;request_handle_bs.c'],['../request__handle__bs_8h.html#a4389d5a3380a1fb1e8df2ebce205a015',1,'request_handle_bs__req_handle_do_nothing(const constants__t_request_handle_i request_handle_bs__req_handle):&#160;request_handle_bs.c']]],
  ['response_5fwrite_5fbs_5f_5falloc_5fwrite_5frequest_5fresponses_5fmalloc',['response_write_bs__alloc_write_request_responses_malloc',['../response__write__bs_8c.html#aff64a0770e92b16a4c6e9e35238d6634',1,'response_write_bs__alloc_write_request_responses_malloc(const t_entier4 response_write_bs__nb_req, t_bool *const response_write_bs__ResponseWrite_allocated):&#160;response_write_bs.c'],['../response__write__bs_8h.html#aff64a0770e92b16a4c6e9e35238d6634',1,'response_write_bs__alloc_write_request_responses_malloc(const t_entier4 response_write_bs__nb_req, t_bool *const response_write_bs__ResponseWrite_allocated):&#160;response_write_bs.c']]],
  ['response_5fwrite_5fbs_5f_5fgetall_5fresponsewrite_5fstatuscode',['response_write_bs__getall_ResponseWrite_StatusCode',['../response__write__bs_8c.html#a93b2ee76a94f1c49b5d54ed3bc4db70c',1,'response_write_bs__getall_ResponseWrite_StatusCode(const constants__t_WriteValue_i response_write_bs__wvi, t_bool *const response_write_bs__isvalid, constants__t_StatusCode_i *const response_write_bs__sc):&#160;response_write_bs.c'],['../response__write__bs_8h.html#a93b2ee76a94f1c49b5d54ed3bc4db70c',1,'response_write_bs__getall_ResponseWrite_StatusCode(const constants__t_WriteValue_i response_write_bs__wvi, t_bool *const response_write_bs__isvalid, constants__t_StatusCode_i *const response_write_bs__sc):&#160;response_write_bs.c']]],
  ['response_5fwrite_5fbs_5f_5finitialisation',['response_write_bs__INITIALISATION',['../response__write__bs_8c.html#a87f99e01404bfcc305c62f3c3da86bb4',1,'response_write_bs__INITIALISATION(void):&#160;response_write_bs.c'],['../response__write__bs_8h.html#a87f99e01404bfcc305c62f3c3da86bb4',1,'response_write_bs__INITIALISATION(void):&#160;response_write_bs.c']]],
  ['response_5fwrite_5fbs_5f_5freset_5fresponsewrite',['response_write_bs__reset_ResponseWrite',['../response__write__bs_8c.html#a0dd613fa283fea4c3293f446689dd792',1,'response_write_bs__reset_ResponseWrite(void):&#160;response_write_bs.c'],['../response__write__bs_8h.html#a0dd613fa283fea4c3293f446689dd792',1,'response_write_bs__reset_ResponseWrite(void):&#160;response_write_bs.c']]],
  ['response_5fwrite_5fbs_5f_5fset_5fresponsewrite_5fstatuscode',['response_write_bs__set_ResponseWrite_StatusCode',['../response__write__bs_8c.html#afedb0bf18939001ff0bf505bd3d4c4f3',1,'response_write_bs__set_ResponseWrite_StatusCode(const constants__t_WriteValue_i response_write_bs__wvi, const constants__t_StatusCode_i response_write_bs__sc):&#160;response_write_bs.c'],['../response__write__bs_8h.html#afedb0bf18939001ff0bf505bd3d4c4f3',1,'response_write_bs__set_ResponseWrite_StatusCode(const constants__t_WriteValue_i response_write_bs__wvi, const constants__t_StatusCode_i response_write_bs__sc):&#160;response_write_bs.c']]],
  ['response_5fwrite_5fbs_5f_5fwrite_5fwriteresponse_5fmsg_5fout',['response_write_bs__write_WriteResponse_msg_out',['../response__write__bs_8c.html#ae0b17d8bf82ba04447dba66e626e07fc',1,'response_write_bs__write_WriteResponse_msg_out(const constants__t_msg_i response_write_bs__msg_out):&#160;response_write_bs.c'],['../response__write__bs_8h.html#ae0b17d8bf82ba04447dba66e626e07fc',1,'response_write_bs__write_WriteResponse_msg_out(const constants__t_msg_i response_write_bs__msg_out):&#160;response_write_bs.c']]]
];
