var searchData=
[
  ['initialisation',['INITIALISATION',['../toolkit__header__init_8c.html#adca460a41bc8093957751b38b59d3bba',1,'INITIALISATION(void):&#160;toolkit_header_init.c'],['../toolkit__header__init_8h.html#adca460a41bc8093957751b38b59d3bba',1,'INITIALISATION(void):&#160;toolkit_header_init.c']]],
  ['io_5fdispatch_5fmgr_5f_5fclient_5factivate_5fnew_5fsession',['io_dispatch_mgr__client_activate_new_session',['../io__dispatch__mgr_8c.html#a07960c2955428053226ec665eeefbc23',1,'io_dispatch_mgr__client_activate_new_session(const constants__t_channel_config_idx_i io_dispatch_mgr__channel_config_idx, const constants__t_user_i io_dispatch_mgr__user, t_bool *const io_dispatch_mgr__bres):&#160;io_dispatch_mgr.c'],['../io__dispatch__mgr_8h.html#a07960c2955428053226ec665eeefbc23',1,'io_dispatch_mgr__client_activate_new_session(const constants__t_channel_config_idx_i io_dispatch_mgr__channel_config_idx, const constants__t_user_i io_dispatch_mgr__user, t_bool *const io_dispatch_mgr__bres):&#160;io_dispatch_mgr.c']]],
  ['io_5fdispatch_5fmgr_5f_5fclient_5fchannel_5fconnected_5fevent',['io_dispatch_mgr__client_channel_connected_event',['../io__dispatch__mgr_8c.html#a3b204b2cacd1aa1f0f83c79a0ca74867',1,'io_dispatch_mgr__client_channel_connected_event(const constants__t_channel_config_idx_i io_dispatch_mgr__channel_config_idx, const constants__t_channel_i io_dispatch_mgr__channel):&#160;io_dispatch_mgr.c'],['../io__dispatch__mgr_8h.html#a3b204b2cacd1aa1f0f83c79a0ca74867',1,'io_dispatch_mgr__client_channel_connected_event(const constants__t_channel_config_idx_i io_dispatch_mgr__channel_config_idx, const constants__t_channel_i io_dispatch_mgr__channel):&#160;io_dispatch_mgr.c']]],
  ['io_5fdispatch_5fmgr_5f_5fclient_5freactivate_5fsession_5fnew_5fuser',['io_dispatch_mgr__client_reactivate_session_new_user',['../io__dispatch__mgr_8c.html#aa107d78c4f71a0d1af9ffdcf8f6c9877',1,'io_dispatch_mgr__client_reactivate_session_new_user(const constants__t_session_i io_dispatch_mgr__session, const constants__t_user_i io_dispatch_mgr__user, constants__t_StatusCode_i *const io_dispatch_mgr__ret):&#160;io_dispatch_mgr.c'],['../io__dispatch__mgr_8h.html#aa107d78c4f71a0d1af9ffdcf8f6c9877',1,'io_dispatch_mgr__client_reactivate_session_new_user(const constants__t_session_i io_dispatch_mgr__session, const constants__t_user_i io_dispatch_mgr__user, constants__t_StatusCode_i *const io_dispatch_mgr__ret):&#160;io_dispatch_mgr.c']]],
  ['io_5fdispatch_5fmgr_5f_5fclient_5fsecure_5fchannel_5ftimeout',['io_dispatch_mgr__client_secure_channel_timeout',['../io__dispatch__mgr_8c.html#aac8325d531d5e3411accccf63fc7a019',1,'io_dispatch_mgr__client_secure_channel_timeout(const constants__t_channel_config_idx_i io_dispatch_mgr__channel_config_idx):&#160;io_dispatch_mgr.c'],['../io__dispatch__mgr_8h.html#aac8325d531d5e3411accccf63fc7a019',1,'io_dispatch_mgr__client_secure_channel_timeout(const constants__t_channel_config_idx_i io_dispatch_mgr__channel_config_idx):&#160;io_dispatch_mgr.c']]],
  ['io_5fdispatch_5fmgr_5f_5fclient_5fsend_5fclose_5fsession_5frequest',['io_dispatch_mgr__client_send_close_session_request',['../io__dispatch__mgr_8c.html#a2da80301d43515e2775e070b9c289b1c',1,'io_dispatch_mgr__client_send_close_session_request(const constants__t_session_i io_dispatch_mgr__session, constants__t_StatusCode_i *const io_dispatch_mgr__ret):&#160;io_dispatch_mgr.c'],['../io__dispatch__mgr_8h.html#a2da80301d43515e2775e070b9c289b1c',1,'io_dispatch_mgr__client_send_close_session_request(const constants__t_session_i io_dispatch_mgr__session, constants__t_StatusCode_i *const io_dispatch_mgr__ret):&#160;io_dispatch_mgr.c']]],
  ['io_5fdispatch_5fmgr_5f_5fclient_5fsend_5fservice_5frequest',['io_dispatch_mgr__client_send_service_request',['../io__dispatch__mgr_8c.html#a87dee35ad0a38781e0b087f1cc0ecbbd',1,'io_dispatch_mgr__client_send_service_request(const constants__t_session_i io_dispatch_mgr__session, const constants__t_msg_i io_dispatch_mgr__req_msg, constants__t_StatusCode_i *const io_dispatch_mgr__ret):&#160;io_dispatch_mgr.c'],['../io__dispatch__mgr_8h.html#a87dee35ad0a38781e0b087f1cc0ecbbd',1,'io_dispatch_mgr__client_send_service_request(const constants__t_session_i io_dispatch_mgr__session, const constants__t_msg_i io_dispatch_mgr__req_msg, constants__t_StatusCode_i *const io_dispatch_mgr__ret):&#160;io_dispatch_mgr.c']]],
  ['io_5fdispatch_5fmgr_5f_5fclose_5fall_5factive_5fconnections',['io_dispatch_mgr__close_all_active_connections',['../io__dispatch__mgr_8c.html#a1f81cca3384084d9d21be616b0d29f7e',1,'io_dispatch_mgr__close_all_active_connections(t_bool *const io_dispatch_mgr__bres):&#160;io_dispatch_mgr.c'],['../io__dispatch__mgr_8h.html#a1f81cca3384084d9d21be616b0d29f7e',1,'io_dispatch_mgr__close_all_active_connections(t_bool *const io_dispatch_mgr__bres):&#160;io_dispatch_mgr.c']]],
  ['io_5fdispatch_5fmgr_5f_5fget_5fmsg_5fheader_5ftype',['io_dispatch_mgr__get_msg_header_type',['../io__dispatch__mgr_8c.html#aa7c41a93454d54024e0a1fab9aa2d230',1,'io_dispatch_mgr__get_msg_header_type(const constants__t_msg_type_i io_dispatch_mgr__msg_typ, constants__t_msg_header_type_i *const io_dispatch_mgr__header_type):&#160;io_dispatch_mgr.c'],['../io__dispatch__mgr_8h.html#aa7c41a93454d54024e0a1fab9aa2d230',1,'io_dispatch_mgr__get_msg_header_type(const constants__t_msg_type_i io_dispatch_mgr__msg_typ, constants__t_msg_header_type_i *const io_dispatch_mgr__header_type):&#160;io_dispatch_mgr.c']]],
  ['io_5fdispatch_5fmgr_5f_5fget_5fmsg_5fservice_5fclass',['io_dispatch_mgr__get_msg_service_class',['../io__dispatch__mgr_8c.html#a49c3f13f63d353f9b0868cd9a15309e9',1,'io_dispatch_mgr__get_msg_service_class(const constants__t_msg_type_i io_dispatch_mgr__msg_typ, constants__t_msg_service_class_i *const io_dispatch_mgr__service_class):&#160;io_dispatch_mgr.c'],['../io__dispatch__mgr_8h.html#a49c3f13f63d353f9b0868cd9a15309e9',1,'io_dispatch_mgr__get_msg_service_class(const constants__t_msg_type_i io_dispatch_mgr__msg_typ, constants__t_msg_service_class_i *const io_dispatch_mgr__service_class):&#160;io_dispatch_mgr.c']]],
  ['io_5fdispatch_5fmgr_5f_5finitialisation',['io_dispatch_mgr__INITIALISATION',['../io__dispatch__mgr_8c.html#a3c77139a6d53f1900ab2086628103c2d',1,'io_dispatch_mgr__INITIALISATION(void):&#160;io_dispatch_mgr.c'],['../io__dispatch__mgr_8h.html#a3c77139a6d53f1900ab2086628103c2d',1,'io_dispatch_mgr__INITIALISATION(void):&#160;io_dispatch_mgr.c']]],
  ['io_5fdispatch_5fmgr_5f_5finternal_5fclient_5factivate_5forphaned_5fsession',['io_dispatch_mgr__internal_client_activate_orphaned_session',['../io__dispatch__mgr_8c.html#ac13fa5207d6408886d6d0c22808f5d3e',1,'io_dispatch_mgr__internal_client_activate_orphaned_session(const constants__t_session_i io_dispatch_mgr__session, const constants__t_channel_config_idx_i io_dispatch_mgr__channel_config_idx):&#160;io_dispatch_mgr.c'],['../io__dispatch__mgr_8h.html#ac13fa5207d6408886d6d0c22808f5d3e',1,'io_dispatch_mgr__internal_client_activate_orphaned_session(const constants__t_session_i io_dispatch_mgr__session, const constants__t_channel_config_idx_i io_dispatch_mgr__channel_config_idx):&#160;io_dispatch_mgr.c']]],
  ['io_5fdispatch_5fmgr_5f_5finternal_5fclient_5fcreate_5fsession',['io_dispatch_mgr__internal_client_create_session',['../io__dispatch__mgr_8c.html#aa7b25d162c376046b6d650eac3476264',1,'io_dispatch_mgr__internal_client_create_session(const constants__t_session_i io_dispatch_mgr__session, const constants__t_channel_config_idx_i io_dispatch_mgr__channel_config_idx):&#160;io_dispatch_mgr.c'],['../io__dispatch__mgr_8h.html#aa7b25d162c376046b6d650eac3476264',1,'io_dispatch_mgr__internal_client_create_session(const constants__t_session_i io_dispatch_mgr__session, const constants__t_channel_config_idx_i io_dispatch_mgr__channel_config_idx):&#160;io_dispatch_mgr.c']]],
  ['io_5fdispatch_5fmgr_5f_5freceive_5fmsg_5fbuffer',['io_dispatch_mgr__receive_msg_buffer',['../io__dispatch__mgr_8c.html#a8bc52eeba98bcf8fc1b0e80ded3d1cf5',1,'io_dispatch_mgr__receive_msg_buffer(const constants__t_channel_i io_dispatch_mgr__channel, const constants__t_byte_buffer_i io_dispatch_mgr__buffer, const constants__t_request_context_i io_dispatch_mgr__request_context):&#160;io_dispatch_mgr.c'],['../io__dispatch__mgr_8h.html#a8bc52eeba98bcf8fc1b0e80ded3d1cf5',1,'io_dispatch_mgr__receive_msg_buffer(const constants__t_channel_i io_dispatch_mgr__channel, const constants__t_byte_buffer_i io_dispatch_mgr__buffer, const constants__t_request_context_i io_dispatch_mgr__request_context):&#160;io_dispatch_mgr.c']]],
  ['io_5fdispatch_5fmgr_5f_5fsecure_5fchannel_5flost',['io_dispatch_mgr__secure_channel_lost',['../io__dispatch__mgr_8c.html#a714b78bb2355b4c2e2f9297942a470b6',1,'io_dispatch_mgr__secure_channel_lost(const constants__t_channel_i io_dispatch_mgr__channel):&#160;io_dispatch_mgr.c'],['../io__dispatch__mgr_8h.html#a714b78bb2355b4c2e2f9297942a470b6',1,'io_dispatch_mgr__secure_channel_lost(const constants__t_channel_i io_dispatch_mgr__channel):&#160;io_dispatch_mgr.c']]],
  ['io_5fdispatch_5fmgr_5f_5fserver_5fchannel_5fconnected_5fevent',['io_dispatch_mgr__server_channel_connected_event',['../io__dispatch__mgr_8c.html#af85429bde9e48d8e861023a89c3e69ee',1,'io_dispatch_mgr__server_channel_connected_event(const constants__t_endpoint_config_idx_i io_dispatch_mgr__endpoint_config_idx, const constants__t_channel_config_idx_i io_dispatch_mgr__channel_config_idx, const constants__t_channel_i io_dispatch_mgr__channel, t_bool *const io_dispatch_mgr__bres):&#160;io_dispatch_mgr.c'],['../io__dispatch__mgr_8h.html#af85429bde9e48d8e861023a89c3e69ee',1,'io_dispatch_mgr__server_channel_connected_event(const constants__t_endpoint_config_idx_i io_dispatch_mgr__endpoint_config_idx, const constants__t_channel_config_idx_i io_dispatch_mgr__channel_config_idx, const constants__t_channel_i io_dispatch_mgr__channel, t_bool *const io_dispatch_mgr__bres):&#160;io_dispatch_mgr.c']]]
];
