#!/bin/bash

# Copyright (C) 2018 Systerel and others.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

CTEST_FILE=$1

if [ -z "$CTEST_FILE" ]; then
    echo "Usage: $1 CTestTestfile.cmake"
    echo
    echo "Transforms a CTestTestfile.cmake test plan so that all paths are"
    echo "relative, and outputs it on STDOUT."
    exit 1
fi

src_dir=$(grep 'Source directory: ' $CTEST_FILE | awk '{print $4}')
sed "s|${src_dir}|..|g" $CTEST_FILE
